OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/ai/enemy_controller.c File Reference
enemy_controller.c File Reference
#include "enemy_controller.h"
#include "../graphics/render.h"
Functions
void init_enemy (player_info_t *enemy, _Bool random, time_t timeout_move, double fov, double range, int num_positions, vector_t *pos)
Initialize an AI controller.
void free_controllers ()
Free the memory allocated by init_enemy()
int handle_enemy (enemy_ctrl_t *enm)
void handle_enemies ()
Handles all of the enemies Calls handle_enemy in each of the controllers to do operations over them.
Variables
static enemy_ctrl_t * controllers = ((void *)0)
static int num_controllers = 0
time_t time_counter
player_info_t player
map_t map
Function Documentation
handle_enemy()
int handle_enemy (enemy_ctrl_t * enm)
Definition at line 55 of file enemy_controller.c.
References abs_double(), map::columns, enemy_ctrl::curr_dest, enemy_ctrl::curr_idx, degree(), player_info::direction, ray_hit::distance, enemy_ctrl::fov, gun_instance::gun, player_info::gun_index, player_info::guns, player_info::health, ray_hit::hit, enemy_ctrl::last_op, controls_t::lb_held_down, map::lines, controls_t::movement, player_info::movm, normalize(), enemy_ctrl::num_positions, player, enemy_ctrl::player, player_info::position, enemy_ctrl::positions, enemy_ctrl::random, enemy_ctrl::range, gun::range, shoot_ray(), time_counter, enemy_ctrl::timeout_movm, vec_mag(), vector::x, and vector::y.
Variable Documentation
controllers
enemy_ctrl_t* controllers = ((void *)0) static
Definition at line 4 of file enemy_controller.c.
map
map_t map extern
Definition at line 29 of file level_manager.c.
num_controllers
int num_controllers = 0 static
Definition at line 6 of file enemy_controller.c.
player
player_info_t player extern
Definition at line 13 of file player.c.
time_counter
time_t time_counter extern
Definition at line 10 of file timer.c.