OPERATION M.I.N.I.X.: Inventory Menu
Inventory Menu
Functions and data_types related to the inventory popup menu.
Enumerations
enum menu_state { CLOSED, DISPLAYING }
State of a popup menu.
Functions
enum menu_state get_inv_menu_state ()
State of the inventory menu.
void display_menu (gun_instance_t *guns, int num_guns)
Display gun selection menu.
Detailed Description
Functions and data_types related to the inventory popup menu.
Enumeration Type Documentation
menu_state
enum menu_state
State of a popup menu.
Enumerator
CLOSED
Menu is closed.
DISPLAYING
Menu is being displayed.
Definition at line 19 of file menu.h.
Function Documentation
display_menu()
void display_menu (gun_instance_t * guns, int num_guns)
Display gun selection menu.
Definition at line 23 of file menu.c.
References CLOSED, DISPLAYING, draw_mouse(), draw_rect(), draw_sprite(), END_M_GAME, END_S_GAME, g_data, get_state(), player_info::gun_index, gun_menu_state, guns, graphics_data::h_res, idx, controls_t::lb_single_tap, gun::menu_sprite, controls_t::mouse_pos, player_info::movm, MP_GAME, ms_detect_collision(), player, set_state(), state, switch_gun(), sprite::texture_size, graphics_data::v_res, vector::x, coordinate::x, pair::x, vector::y, coordinate::y, and pair::y.
get_inv_menu_state()
enum menu_state get_inv_menu_state ()
State of the inventory menu.
Returns
State of the inventory menu
Definition at line 15 of file menu.c.