OPERATION M.I.N.I.X.: Controls
Controls
Functions for treating player input and converting to movement.
Data Structures
struct settings
Settings structure used to store settings.
struct kbd_ctrl_state
Structure that stores the state of keyboard related controls.
struct controls_t
Controls structure that stores all control related objects of a certain entity.
Typedefs
typedef struct packet packet_t
Mouse Packet received from the KBC.
typedef struct settings settings_t
Settings structure used to store settings.
typedef enum key_state key_state_t
Key states.
Enumerations
enum key_state { KEY_UP, KEY_DOWN }
Key states.
Functions
void() init_settings ()
Initializes the settings with default values.
settings_t() retrieve_settings ()
Gets the current settings.
void() handle_kbd_evt ()
Handles a keyboard event after an interrupt Calls kbc_ih() Evaluates important information such as make codes and double bytes Calls kbd_parse_data to use that information.
void() kbd_parse_data (__uint8_t *bytes, size_t size, _Bool make)
Parses keyboard data Finds usefull information for movement and activates variables in controls_t object from player.
void() handle_mouse_evt ()
Handles a mouse event after an interrupt Calls mouse_ih() Evaluates important information such as current packet's index Detects invalid first bytes Calls parse_packet and mouse_parse_data to use that information.
void() mouse_parse_data ()
Parses keyboard data Finds usefull information for movement and interaction and activates variables in controls_t object from player.
_Bool() ms_detect_collision (vector_t ms_pos, pair_t button_pos, coordinate_t button_size)
Detects if the mouse is within the boundings of a rectangle.
Detailed Description
Functions for treating player input and converting to movement.
Typedef Documentation
key_state_t
typedef enum key_state key_state_t
Key states.
packet_t
typedef struct packet packet_t
Mouse Packet received from the KBC.
Definition at line 1 of file controls.h.
settings_t
typedef struct settings settings_t
Settings structure used to store settings.
Enumeration Type Documentation
key_state
enum key_state
Key states.
Enumerator
KEY_UP
KEY_DOWN
Definition at line 47 of file controls.h.
Function Documentation
handle_kbd_evt()
void() handle_kbd_evt ()
Handles a keyboard event after an interrupt Calls kbc_ih() Evaluates important information such as make codes and double bytes Calls kbd_parse_data to use that information.
Definition at line 37 of file controls.c.
References KBC_BREAK_CODE, KBC_DOUBLE_BYTE, kbc_ih(), kbd_parse_data(), last_kb_byte, lastDoubleByte, and valid_kb_byte.
handle_mouse_evt()
void() handle_mouse_evt ()
Handles a mouse event after an interrupt Calls mouse_ih() Evaluates important information such as current packet's index Detects invalid first bytes Calls parse_packet and mouse_parse_data to use that information.
Definition at line 88 of file controls.c.
References currPkt, last_mouse_byte, MOUSE_FIRST_BIT, mouse_ih(), mouse_parse_data(), ms_data, ms_idx, parse_packet(), and valid_mouse_byte.
init_settings()
void() init_settings ()
Initializes the settings with default values.
Definition at line 112 of file controls.c.
References settings::fov, settings::mouse_color, and settings::mouse_sensitivity.
kbd_parse_data()
void() kbd_parse_data (__uint8_t * bytes, size_t size, _Bool make)
Parses keyboard data Finds usefull information for movement and activates variables in controls_t object from player.
Parameters
bytes Bytes of the keyboard (can be a double byte)
size Size of the keyboard data
make True if the keyboard data is a make code
Definition at line 62 of file controls.c.
References A_KEY, kbd_ctrl_state::crouch, D_KEY, kbd_ctrl_state::gun_menu, controls_t::kbd_state, controls_t::movement, player_info::movm, kbd_ctrl_state::nums_press, PARSE_BREAK_CODE, player, PT_0, PT_1, PT_CTRL, PT_SHIFT, Q_KEY, S_KEY, kbd_ctrl_state::sprint, W_KEY, vector::x, kbd_ctrl_state::x_neg, kbd_ctrl_state::x_pos, vector::y, kbd_ctrl_state::y_neg, and kbd_ctrl_state::y_pos.
mouse_parse_data()
void() mouse_parse_data ()
Parses keyboard data Finds usefull information for movement and interaction and activates variables in controls_t object from player.
Definition at line 122 of file controls.c.
References CLOSED, currPkt, g_data, GAME, get_state(), gun_menu_state, graphics_data::h_res, controls_t::lb_held_down, controls_t::mouse_desl, controls_t::mouse_pkt, controls_t::mouse_pos, settings::mouse_sensitivity, player_info::movm, MP_GAME, player, graphics_data::v_res, vector::x, and vector::y.
ms_detect_collision()
_Bool() ms_detect_collision (vector_t ms_pos, pair_t button_pos, coordinate_t button_size)
Detects if the mouse is within the boundings of a rectangle.
Parameters
ms_pos Position of the mouse
button_pos Top left corner position of the button
button_size Width and height of the button
Definition at line 30 of file controls.c.
References vector::x, and vector::y.
retrieve_settings()
settings_t() retrieve_settings ()
Gets the current settings.
Returns
The current settings.
Definition at line 118 of file controls.c.
References settings.