OPERATION M.I.N.I.X.: Main Menu
Main Menu
Functions to display the main menu and functionalities.
Functions
void render_menu ()
Render the main menu.
void render_mp_menu ()
Renders the multiplayer connection screen.
void render_win_lose_screen ()
Renders a win/lose screen according to the player's condition.
date_t * get_menu_date ()
Returns the date object stored in the main menu.
void render_disconnect_screen ()
Renders the disconnected screen.
Detailed Description
Functions to display the main menu and functionalities.
Function Documentation
get_menu_date()
date_t* get_menu_date ()
Returns the date object stored in the main menu.
render_disconnect_screen()
void render_disconnect_screen ()
Renders the disconnected screen.
Definition at line 139 of file main_menu.c.
References draw_mouse(), draw_sprite(), g_data, graphics_data::h_res, controls_t::lb_held_down, MAIN_MENU, controls_t::mouse_pos, player_info::movm, ms_detect_collision(), player, set_state(), pair::x, and pair::y.
render_menu()
void render_menu ()
Render the main menu.
Definition at line 22 of file main_menu.c.
References date::day, draw_mouse(), draw_sprite(), EXIT, g_data, get_curr_date(), gm_init_game(), graphics_data::h_res, date::hour, controls_t::lb_held_down, date::min, date::month, controls_t::mouse_pos, player_info::movm, MP_MENU, ms_detect_collision(), player, render_number(), render_time_number(), date::sec, set_state(), pair::x, pair::y, and date::year.
render_mp_menu()
void render_mp_menu ()
Renders the multiplayer connection screen.
Definition at line 80 of file main_menu.c.
References draw_mouse(), draw_sprite(), g_data, graphics_data::h_res, INIT, controls_t::lb_held_down, MAIN_MENU, controls_t::mouse_pos, player_info::movm, ms_detect_collision(), player, set_network_state(), set_state(), pair::x, and pair::y.
render_win_lose_screen()
void render_win_lose_screen ()
Renders a win/lose screen according to the player's condition.
Definition at line 96 of file main_menu.c.
References draw_mouse(), draw_sprite(), g_data, get_curr_lvl(), get_state(), gm_init_game(), graphics_data::h_res, LAST_LVL, controls_t::lb_held_down, LOSE_GAME, MAIN_MENU, controls_t::mouse_pos, player_info::movm, MP_MENU, ms_detect_collision(), player, set_state(), WIN_GAME, pair::x, and pair::y.