OPERATION M.I.N.I.X.: Video Graphics
Video Graphics
Functions used to interface with the graphics card.
Data Structures
struct graphics_data
Struct that stores relevant information about the currently chosen video mode.
Functions
__uint8_t() ceil_to_bytes (__uint8_t bits)
Returns number of bytes needed to represent that ammout of bits.
unsigned int() get_mem_size (vbe_mode_info_t *info)
Returns memory size.
int() vbe_get_info (__uint16_t mode, vbe_mode_info_t *info)
Reads information of the graphics card.
void *() vg_init (__uint16_t mode)
Function to initialize a graphics mode.
int() page_flip ()
Swaps the page buffer with the drawing buffer.
int() reset_to_text_mode ()
Resetting minix to text mode.
int() set_px (unsigned x_pos, unsigned y_pos, __uint32_t color)
Sets a pixel to a desired color in a position of the page buffer.
int() vg_draw_hor_line (__uint16_t x, __uint16_t y, __uint16_t len, __uint32_t color)
Draws a horizontal line in the page buffer.
int() draw_rect (__uint16_t x, __uint16_t y, __uint16_t x_end, __uint16_t y_end, __uint32_t color)
Draws a rectangle.
int() darken_rect (__uint16_t x, __uint16_t y, __uint16_t x_end, __uint16_t y_end, double factor)
Darkens an area of the screen.
int() darken_hor_line (__uint16_t x, __uint16_t y, __uint16_t len, double factor)
Darkens an horizontal line of the screen.
int() darken_pix (__uint16_t x, __uint16_t y, double factor)
Darkens a pixel of the screen.
int() clear_screen ()
Clears the screen.
int() draw_rect_sprite (pair_t *end_pos, pair_t *offset, pair_t *bounding_box, sprite_t *sprite, double sprite_dist, double factor)
Draws a sprite in a specified position of the map creating a distance between the player and that sprite. Adapted from the following tutorial: https://lodev.org/cgtutor/raycasting3.html.
int() draw_darken_rect (__uint16_t x, __uint16_t y, __uint16_t x_end, __uint16_t y_end, __uint32_t color, double factor, double dist)
Draws a rectangle that darkens with distance and is not rendered behind walls.
int() put_buffer ()
Puts the current buffer to the screen.
int() draw_sprite (pair_t *start_pos, sprite_t *sprite)
Draws a sprite on the screen.
int() draw_sprite_color_mask (pair_t *start_pos, sprite_t *sprite, __uint32_t color)
Draws a sprite on the screen, using its 'shape' as a color mask.
__uint32_t darken (__uint32_t color, double factor)
Darkens a color by a factor.
Variables
graphics_data g_data
Detailed Description
Functions used to interface with the graphics card.
Function Documentation
ceil_to_bytes()
__uint8_t() ceil_to_bytes (__uint8_t bits)
Returns number of bytes needed to represent that ammout of bits.
Parameters
bits - The number of bits
Returns
uint8_t - Number of bytes
Definition at line 16 of file video_graphics.c.
clear_screen()
int() clear_screen ()
Clears the screen.
Definition at line 179 of file video_graphics.c.
References graphics_data::bytes_per_px, g_data, graphics_data::h_res, graphics_data::page_address, and graphics_data::v_res.
darken()
__uint32_t darken (__uint32_t color, double factor)
Darkens a color by a factor.
Parameters
color the color to be darkened
factor the factor to darken
Returns
the darkened color
Definition at line 243 of file video_graphics.h.
References color::rgb.
darken_hor_line()
int() darken_hor_line (__uint16_t x, __uint16_t y, __uint16_t len, double factor)
Darkens an horizontal line of the screen.
Quite useful for menus to obscure some part of the game
Parameters
x the x position (the column)
y the y position (the line)
len the width of the line
factor The factor used by the darken function
Returns
0 if returns ok.
Definition at line 306 of file video_graphics.c.
References darken_pix().
darken_pix()
int() darken_pix (__uint16_t x, __uint16_t y, double factor)
Darkens a pixel of the screen.
Parameters
x the x position (the column)
y the y position (the line)
factor The factor used by the darken function
Returns
0 if returns ok.
Definition at line 314 of file video_graphics.c.
References darken(), g_data, graphics_data::h_res, graphics_data::page_address, and graphics_data::v_res.
darken_rect()
int() darken_rect (__uint16_t x, __uint16_t y, __uint16_t x_end, __uint16_t y_end, double factor)
Darkens an area of the screen.
Quite usefull for menus to obscure some part of the game
Parameters
x the x position (the column)
y the y position (the line)
x_end the x ending position
y_end the y ending position
factor The factor used by the darken function
Returns
0 if returns ok.
Definition at line 297 of file video_graphics.c.
References darken_hor_line().
draw_darken_rect()
int() draw_darken_rect (__uint16_t x, __uint16_t y, __uint16_t x_end, __uint16_t y_end, __uint32_t color, double factor, double dist)
Draws a rectangle that darkens with distance and is not rendered behind walls.
Parameters
x X position on screen
y Y position on screen
x_end Final X position on screen
y_end Final Y position on screen
color Color of rectangle
factor Darkening factor of color
dist Dist to the rectangle
Definition at line 216 of file video_graphics.c.
References darken(), and draw_dists_hor_line().
draw_rect()
int() draw_rect (__uint16_t x, __uint16_t y, __uint16_t x_end, __uint16_t y_end, __uint32_t color)
Draws a rectangle.
Parameters
x the x position (the column)
y the y position (the line)
x_end the x ending position
y_end the y ending position
color the color of the rectangle
Returns
0 if returns ok.
Definition at line 197 of file video_graphics.c.
References vg_draw_hor_line().
draw_rect_sprite()
int() draw_rect_sprite (pair_t * end_pos, pair_t * offset, pair_t * bounding_box, sprite_t * sprite, double sprite_dist, double factor)
Draws a sprite in a specified position of the map creating a distance between the player and that sprite. Adapted from the following tutorial: https://lodev.org/cgtutor/raycasting3.html.
The initial and final values should be calculated beforehand The function will draw the pixels from offset to end_pos, skipping/copying the necessary colors to apply the scaling With this scaling method, a sprite will appear further away/close to the player according to its position
Parameters
offset Start position
end_pos End position
bounding_box Width and height of the object to be drawn
sprite Sprite to be drawn
sprite_dist Distance from the player to the sprite to know if it is behind a wall and that which parts should be drawn
factor Factor of darkening color to make the object look farther away
Definition at line 228 of file video_graphics.c.
References darken(), line::dist, g_data, graphics_data::h_res, sprite::invis_color, graphics_data::lines, sprite::map, MAX_SPRITE_HEIGHT, MAX_SPRITE_WIDTH, set_px(), START_DARKEN, sprite::texture_size, graphics_data::v_res, coordinate::x, pair::x, sprite::x_offset, coordinate::y, pair::y, and sprite::y_offset.
draw_sprite()
int() draw_sprite (pair_t * start_pos, sprite_t * sprite)
Draws a sprite on the screen.
Parameters
start_pos Pointer to the position on screen where the sprite will be drawn.
sprite Pointer to the sprite being drawn.
Returns
OK if no errors occurred.
Definition at line 328 of file video_graphics.c.
References g_data, graphics_data::h_res, sprite::invis_color, sprite::map, set_px(), sprite::texture_size, graphics_data::v_res, coordinate::x, pair::x, coordinate::y, and pair::y.
draw_sprite_color_mask()
int() draw_sprite_color_mask (pair_t * start_pos, sprite_t * sprite, __uint32_t color)
Draws a sprite on the screen, using its 'shape' as a color mask.
Parameters
start_pos Pointer to the position on screen where the sprite will be drawn.
sprite Pointer to the sprite being drawn.
color Color being used to draw the sprite.
Returns
OK if no errors occurred.
Definition at line 347 of file video_graphics.c.
References g_data, graphics_data::h_res, sprite::invis_color, sprite::map, set_px(), sprite::texture_size, graphics_data::v_res, coordinate::x, pair::x, coordinate::y, and pair::y.
get_mem_size()
unsigned int() get_mem_size (vbe_mode_info_t * info)
Returns memory size.
Parameters
info - VBE Mode info block
Returns size of vram in bytes
Definition at line 26 of file video_graphics.c.
References ceil_to_bytes().
page_flip()
int() page_flip ()
Swaps the page buffer with the drawing buffer.
Returns
0 if returns ok
Definition at line 142 of file video_graphics.c.
References graphics_data::drawing_address, g_data, graphics_data::page_address, graphics_data::physical_drawing_scanline, graphics_data::physical_page_scanline, graphics_data::physical_third_scanline, graphics_data::third_address, VBE_BIOS_CALL, VBE_CALL, VBE_SET_DISPLAY_FUNC, and VBE_SET_DISPLAY_RETRACE.
put_buffer()
int() put_buffer ()
Puts the current buffer to the screen.
Returns
OK if no errors occurred.
Definition at line 366 of file video_graphics.c.
References page_flip().
reset_to_text_mode()
int() reset_to_text_mode ()
Resetting minix to text mode.
Definition at line 168 of file video_graphics.c.
References graphics_data::drawing_address, g_data, graphics_data::lines, graphics_data::page_address, and graphics_data::third_address.
set_px()
int() set_px (unsigned x_pos, unsigned y_pos, __uint32_t color)
Sets a pixel to a desired color in a position of the page buffer.
Parameters
x_pos the x position in pixels counting from the left
y_pos the y position in pixels counting from the top
color the color to be drawn
Returns
0 if returns ok.
Definition at line 105 of file video_graphics.h.
References g_data, graphics_data::h_res, and graphics_data::page_address.
vbe_get_info()
int() vbe_get_info (__uint16_t mode, vbe_mode_info_t * info)
Reads information of the graphics card.
Parameters
mode - The configuration of the graphics card
info - VBE Mode info block to be filled
Definition at line 33 of file video_graphics.c.
References map, VBE_BIOS_CALL, VBE_CALL, and VBE_INFO.
vg_draw_hor_line()
int() vg_draw_hor_line (__uint16_t x, __uint16_t y, __uint16_t len, __uint32_t color)
Draws a horizontal line in the page buffer.
Parameters
x the x starting position
y the y starting position
len the length of the line
color the color of the line
Returns
0 if returns ok
Definition at line 189 of file video_graphics.c.
References set_px().
vg_init()
void*() vg_init (__uint16_t mode)
Function to initialize a graphics mode.
Starts a video mode and initializes the g_data structure.
Parameters
mode Graphical mode
mode the mode to be set
Returns
pointer to the virtual memory mapped
Definition at line 68 of file video_graphics.c.
References graphics_data::bits_per_px, graphics_data::bytes_per_px, ceil_to_bytes(), graphics_data::drawing_address, g_data, get_mem_size(), graphics_data::h_res, LINEAR_FRAME_BUFFER, graphics_data::lines, graphics_data::page_address, graphics_data::physical_drawing_scanline, graphics_data::physical_page_scanline, graphics_data::physical_third_scanline, graphics_data::third_address, graphics_data::v_res, VBE_BIOS_CALL, VBE_CALL, VBE_FUNC, vbe_get_info(), and graphics_data::vram.
Variable Documentation
g_data
graphics_data g_data extern
Definition at line 14 of file video_graphics.c.