OPERATION M.I.N.I.X.: KBC functions
KBC functions
Functions for using the KBC interface.
Functions
int() kb_subscribe_int (__uint8_t *bit_no)
Subscribes the keyboard interrupts.
int() mouse_subscribe_int (__uint8_t *bit_no)
Subscribes the mouse interrupts.
int() kb_unsubscribe_int ()
Unsubscribes the keyboard interrupts.
int() mouse_unsubscribe_int ()
Unsubscribes the mouse interrupts.
int() kbc_disable_int ()
Checks the kbc status according to the flags desired in mask Example: mask = KBC_IN_FULL | KC_PARITY_ERR will checks if the input buffer is full and there is a parity error If that happens, returns err If you want to check the output buffer, select checkBuffer to true If the output buffer is full means that there is no error and is able to read.
int() kbc_enable_int ()
Enables interrupts from the kbc (keyboard + mouse)
int() write_byte_kbc (__uint8_t byte)
Issues a command to the kbc.
int() read_byte_kbc (__uint8_t *byte)
Reads the return value of a command sent to the kbc.
int() write_arg_kbc (__uint8_t byte)
Writes an argument to a command to the kbc.
int() write_kbc_cmd_byte (__uint8_t byte)
Writes a command byte to the kbc.
int() reset_cmd_byte ()
Function to reset the command byte.
int() enable_data_reporting ()
Enables data reporting from mouse.
int() disable_data_reporting ()
Disables data reporting from mouse.
int() write_ms_cmd (size_t arg_size, __uint8_t *args)
Issues a command to the kbc.
int() read_ms_cmd (size_t arg_size, __uint8_t *args)
Function to read the result of a mouse command.
int() enable_stream ()
Enables stream mode from mouse.
int() enable_remote ()
Enables remote mode from mouse.
int() enable_ms ()
Enables mouse.
int() ms_set_default ()
Sets mouse to default values.
void() int9_to_int16 (__uint8_t lsb, _Bool negative, __int16_t *result)
Turns a 9 bit two's complement number to a 16 bit number.
void() parse_packet (__uint8_t bytes[3], struct packet *pkt)
Turns a 3 byte array into a packet structure.
void() kbc_ih (void)
Interrupt handler for the keyboard.
void() mouse_ih ()
Interrupt handler for the mouse.
Detailed Description
Functions for using the KBC interface.
Function Documentation
disable_data_reporting()
int() disable_data_reporting ()
Disables data reporting from mouse.
Returns
Return OK upon sucess
Definition at line 191 of file kbc.c.
References DISABLE_DATA_REPORT, and write_ms_cmd().
enable_data_reporting()
int() enable_data_reporting ()
Enables data reporting from mouse.
Returns
Return OK upon sucess
Definition at line 186 of file kbc.c.
References ENABLE_DATA_REPORT, and write_ms_cmd().
enable_ms()
int() enable_ms ()
Enables mouse.
Returns
Return OK upon sucess
Definition at line 178 of file kbc.c.
References MOUSE_ENABLE, and write_byte_kbc().
enable_remote()
int() enable_remote ()
Enables remote mode from mouse.
Returns
Return OK upon sucess
Definition at line 206 of file kbc.c.
References disable_data_reporting(), SET_REMOTE_MODE, and write_ms_cmd().
enable_stream()
int() enable_stream ()
Enables stream mode from mouse.
Returns
Return OK upon sucess
Definition at line 196 of file kbc.c.
References disable_data_reporting(), enable_data_reporting(), SET_STREAM_MODE, and write_ms_cmd().
int9_to_int16()
void() int9_to_int16 (__uint8_t lsb, _Bool negative, __int16_t * result)
Turns a 9 bit two's complement number to a 16 bit number.
Parameters
lsb The 8 bit least significant byte.
negative negative.
result The result paramater.
Definition at line 266 of file kbc.c.
kb_subscribe_int()
int() kb_subscribe_int (__uint8_t * bit_no)
Subscribes the keyboard interrupts.
Returns
Return 0 upon success and non-zero otherwise
<Keyboard IRQ line
Definition at line 15 of file kbc.c.
References KB_HOOK_ID, KB_IRQ, and kb_subscribe_result.
kb_unsubscribe_int()
int() kb_unsubscribe_int ()
Unsubscribes the keyboard interrupts.
Returns
Return 0 upon success and non-zero otherwise
Definition at line 29 of file kbc.c.
References kb_subscribe_result.
kbc_disable_int()
int() kbc_disable_int ()
Checks the kbc status according to the flags desired in mask Example: mask = KBC_IN_FULL | KC_PARITY_ERR will checks if the input buffer is full and there is a parity error If that happens, returns err If you want to check the output buffer, select checkBuffer to true If the output buffer is full means that there is no error and is able to read.
Parameters
mask - Pointer to the mask desired
checkBuffer - Pointer to the boolean to return the value of the buffer
Returns
Return 0 upon success and non-zero otherwise
Disables interrupts from the kbc (keyboard + mouse)
Checks if it was previously subscribed. If it was not previously subscribed the function sets a policy.
Returns
Return 0 upon success and non-zero otherwise
Definition at line 37 of file kbc.c.
References kb_subscribe_result, and mouse_subscribe_result.
kbc_enable_int()
int() kbc_enable_int ()
Enables interrupts from the kbc (keyboard + mouse)
Checks if it was previously subscribed and if a policy was set when disabling interrupts. If this is the case, the policy is removed
Returns
Return 0 upon success and non-zero otherwise
Definition at line 46 of file kbc.c.
References kb_subscribe_result, and mouse_subscribe_result.
kbc_ih()
void() kbc_ih (void)
Interrupt handler for the keyboard.
Definition at line 222 of file kbc.c.
References get_status_kbc(), KBC_AUX, KBC_OUT_BUF, KBC_OUT_BUFFER_FULL, KBC_PARITY_ERR, KBC_TIMEOUT_ERR, last_kb_byte, util_sys_inb(), and valid_kb_byte.
mouse_ih()
void() mouse_ih ()
Interrupt handler for the mouse.
Definition at line 242 of file kbc.c.
References get_status_kbc(), KBC_AUX, KBC_OUT_BUF, KBC_OUT_BUFFER_FULL, KBC_PARITY_ERR, KBC_TIMEOUT_ERR, last_mouse_byte, util_sys_inb(), and valid_mouse_byte.
mouse_subscribe_int()
int() mouse_subscribe_int (__uint8_t * bit_no)
Subscribes the mouse interrupts.
Returns
Return 0 upon success and non-zero otherwise
Definition at line 22 of file kbc.c.
References MOUSE_HOOK_ID, MOUSE_IRQ, and mouse_subscribe_result.
mouse_unsubscribe_int()
int() mouse_unsubscribe_int ()
Unsubscribes the mouse interrupts.
Returns
Return 0 upon success and non-zero otherwise
Definition at line 33 of file kbc.c.
References mouse_subscribe_result.
ms_set_default()
int() ms_set_default ()
Sets mouse to default values.
Returns
Return OK upon sucess
Definition at line 214 of file kbc.c.
References disable_data_reporting(), SET_DEFAULTS, and write_ms_cmd().
parse_packet()
void() parse_packet (__uint8_t bytes[3], struct packet * pkt)
Turns a 3 byte array into a packet structure.
Parameters
bytes the 3 byte array
pkt pointer where the result will be put
Definition at line 276 of file kbc.c.
References int9_to_int16(), MOUSE_LB, MOUSE_MB, MOUSE_MSB_X_DELTA, MOUSE_MSB_Y_DELTA, MOUSE_RB, MOUSE_X_OVFL, and MOUSE_Y_OVFL.
read_byte_kbc()
int() read_byte_kbc (__uint8_t * byte)
Reads the return value of a command sent to the kbc.
Has to read the status register and make sure the interrupt handler does not read from the output buffer.
Parameters
value The value where the result will be stored
Returns
Return 0 upon success and non-zero otherwise
Definition at line 103 of file kbc.c.
References get_status_kbc(), KBC_MAX_TRIES, KBC_OUT_BUF, KBC_OUT_BUFFER_FULL, KBC_PARITY_ERR, KBC_TIMEOUT_ERR, and util_sys_inb().
read_ms_cmd()
int() read_ms_cmd (size_t arg_size, __uint8_t * args)
Function to read the result of a mouse command.
Parameters
arg_size Number of returns
args an array of arguments to be recieved
Returns
Return 0 upon success and non-zero otherwise
Definition at line 152 of file kbc.c.
References KBC_MAX_TRIES, and read_byte_kbc().
reset_cmd_byte()
int() reset_cmd_byte ()
Function to reset the command byte.
Returns
Return 0 upon success and non-zero otherwise
Definition at line 260 of file kbc.c.
References write_kbc_cmd_byte().
write_arg_kbc()
int() write_arg_kbc (__uint8_t byte)
Writes an argument to a command to the kbc.
Has to read the status register (checking that the output buffer is empty) and make sure the interrupt handler does not read from the output buffer.
Parameters
value The argument to be written
Returns
Return 0 upon success and non-zero otherwise
Definition at line 81 of file kbc.c.
References get_status_kbc(), KBC_MAX_TRIES, KBC_OUT_BUF, KBC_OUT_BUFFER_FULL, KBC_PARITY_ERR, and KBC_TIMEOUT_ERR.
write_byte_kbc()
int() write_byte_kbc (__uint8_t byte)
Issues a command to the kbc.
Has to read the status register and has to wait for the input buffer to be empty.
Parameters
command The command to be written to the keyboard input buffer
Returns
Return 0 upon success and non-zero otherwise
Definition at line 59 of file kbc.c.
References get_status_kbc(), KBC_IN_BUF, KBC_IN_BUFFER_FULL, KBC_MAX_TRIES, KBC_PARITY_ERR, and KBC_TIMEOUT_ERR.
write_kbc_cmd_byte()
int() write_kbc_cmd_byte (__uint8_t byte)
Writes a command byte to the kbc.
Parameters
command_byte The command byte to be written
Returns
Return 0 upon success and non-zero otherwise
Definition at line 171 of file kbc.c.
References KBC_WRITE_CMD, write_arg_kbc(), and write_byte_kbc().
write_ms_cmd()
int() write_ms_cmd (size_t arg_size, __uint8_t * args)
Issues a command to the kbc.
Has to read the status register and has to wait for the input buffer to be empty. Tries multiple times when recieving acknowledgment errors.
Parameters
arg_size The number of arguments (including the command itself)
args an array of the arguments to be sent
Returns
Return 0 upon success and non-zero otherwise
Definition at line 125 of file kbc.c.
References ACK, KBC_MAX_TRIES, MOUSE_WRITE_CMD, read_byte_kbc(), write_arg_kbc(), and write_byte_kbc().