OPERATION M.I.N.I.X.: Uart
Uart
Functions for using the serial port.
Functions
int() uart_get_line_status (__uint8_t *status)
Gets the line status from the LSR register of the UART.
int() uart_get_line_ctrl (__uint8_t *ctrl)
Gets the line control from the LCR register of the UART.
int() uart_get_int_id (__uint8_t *byte)
Gets the interruption identifier.
int() uart_set_line_ctrl (__uint8_t ctrl)
Writes a control byte to the LCR register of the UART.
int() uart_send_byte (__uint8_t byte)
Sends a byte through the UART.
int() uart_init_fifo ()
Enables UART's fifo and clears both fifo's.
int() uart_set_baud_rate (__uint16_t rate)
Sets the baud rate (rate of symbols) of the UART.
int() uart_receive_byte (__uint8_t *byte)
Checks and receives a byte from the UART.
int() uart_subscribe_int (__uint8_t *bit_no)
Subscribes to UART interrupts.
int() uart_disable_int ()
Disables UART interrupts (given that they are subscribed to).
int() uart_enable_int ()
Enables UART interrupts (given that they are subscribed to).
int() uart_unsubscribe_int ()
Unsubscribes from UART interrupts.
void() uart_ih ()
Uart interrupt handler.
int() init_uart_queues ()
Initializes the queues related to the uart.
int() free_uart_queues ()
Frees the memory allocated by init_uart_queues.
_Bool() uart_recv_front (__int16_t *byte)
Receives the front of the in_fifo.
void() uart_push_transmit (__int16_t byte)
Adds a byte to the transmit queue.
_Bool() transmitter_empty ()
Checks if the transmitter empty interrupt was received, but nothing was sent.
int() uart_set_interrupt_reg (__uint8_t ctrl)
Sets the IER register of the UART.
void() empty_transmit_queue ()
Cancels transmissions.
void() empty_recv_queue ()
Cancels receptions.
void() uart_safe_transmit (__uint8_t byte)
Sends a byte to be transmitted by the uart, checking if it is empty, or pushing it to a queue. To be used only for the first byte sent in a sequence.
Detailed Description
Functions for using the serial port.
Function Documentation
empty_recv_queue()
void() empty_recv_queue ()
Cancels receptions.
Definition at line 229 of file uart.c.
References in_fifo, and queue_clean().
empty_transmit_queue()
void() empty_transmit_queue ()
Cancels transmissions.
Definition at line 225 of file uart.c.
References out_fifo, and queue_clean().
free_uart_queues()
int() free_uart_queues ()
Frees the memory allocated by init_uart_queues.
Definition at line 24 of file uart.c.
References in_fifo, out_fifo, and queue_delete().
init_uart_queues()
int() init_uart_queues ()
Initializes the queues related to the uart.
Definition at line 17 of file uart.c.
References in_fifo, out_fifo, and queue_init().
transmitter_empty()
_Bool() transmitter_empty ()
Checks if the transmitter empty interrupt was received, but nothing was sent.
Returns
True if the interrupt to transmit was called, but nothing was sent.
Definition at line 174 of file uart.c.
References can_send.
uart_disable_int()
int() uart_disable_int ()
Disables UART interrupts (given that they are subscribed to).
Returns
OK if no errors occurred.
Definition at line 40 of file uart.c.
References uart_subscribe_result.
uart_enable_int()
int() uart_enable_int ()
Enables UART interrupts (given that they are subscribed to).
Returns
OK if no errors occurred.
Definition at line 45 of file uart.c.
References uart_subscribe_result.
uart_get_int_id()
int() uart_get_int_id (__uint8_t * byte)
Gets the interruption identifier.
Parameters
[out] byte The identifier
Returns
OK if no errors occurred.
Definition at line 70 of file uart.c.
References COM1_UART_ADDRESS, UART_IIR, and util_sys_inb().
uart_get_line_ctrl()
int() uart_get_line_ctrl (__uint8_t * ctrl)
Gets the line control from the LCR register of the UART.
Parameters
[out] ctrl The line control byte.
Returns
OK if no errors occurred.
Definition at line 65 of file uart.c.
References COM1_UART_ADDRESS, UART_LCR, and util_sys_inb().
uart_get_line_status()
int() uart_get_line_status (__uint8_t * status)
Gets the line status from the LSR register of the UART.
Parameters
[out] status The line status byte.
Returns
OK if no errors occurred.
Definition at line 60 of file uart.c.
References COM1_UART_ADDRESS, UART_LSR, and util_sys_inb().
uart_ih()
void() uart_ih ()
Uart interrupt handler.
Definition at line 179 of file uart.c.
References timer_status_field_val::byte, can_send, IIR_INT, IIR_RECV_DATA_AVAIL, IIR_STATUS, IIR_TRNSMT_EMPTY, in_fifo, INT_MASK, out_fifo, queue_empty(), queue_front(), queue_pop(), queue_push(), UART_ERROR_CODE, uart_get_int_id(), uart_get_line_status(), uart_receive_byte(), and uart_send_byte().
uart_init_fifo()
int() uart_init_fifo ()
Enables UART's fifo and clears both fifo's.
Definition at line 50 of file uart.c.
References COM1_UART_ADDRESS, FIFO_CLR_RCVR, FIFO_CLR_SEND, FIFO_ENABLE, FIFO_ONE_BYTE, and UART_FCR.
uart_push_transmit()
void() uart_push_transmit (__int16_t byte)
Adds a byte to the transmit queue.
Definition at line 168 of file uart.c.
References can_send, out_fifo, and queue_push().
uart_receive_byte()
int() uart_receive_byte (__uint8_t * byte)
Checks and receives a byte from the UART.
Parameters
[out] byte The received byte.
Returns
OK if no errors occurred.
Definition at line 125 of file uart.c.
References COM1_UART_ADDRESS, FIFO_ERR, FRAMING_ERR, OVERRUN_ERR, PARITY_ERR, RECEIVE_DATA, UART_DELAY, uart_get_line_status(), UART_MAX_TRIES, UART_RBR, and util_sys_inb().
uart_recv_front()
_Bool() uart_recv_front (__int16_t * byte)
Receives the front of the in_fifo.
Returns
true if not empty.
Definition at line 156 of file uart.c.
References in_fifo, queue_empty(), queue_front(), and queue_pop().
uart_safe_transmit()
void() uart_safe_transmit (__uint8_t byte)
Sends a byte to be transmitted by the uart, checking if it is empty, or pushing it to a queue. To be used only for the first byte sent in a sequence.
Parameters
byte The byte to be sent.
Definition at line 146 of file uart.h.
References transmitter_empty(), uart_push_transmit(), and uart_send_byte().
uart_send_byte()
int() uart_send_byte (__uint8_t byte)
Sends a byte through the UART.
Parameters
byte The byte to be sent.
Returns
OK if no errors occurred.
Definition at line 108 of file uart.c.
References COM1_UART_ADDRESS, TRANS_HOLD_EMPTY, UART_DELAY, uart_get_line_status(), UART_MAX_TRIES, and UART_THR.
uart_set_baud_rate()
int() uart_set_baud_rate (__uint16_t rate)
Sets the baud rate (rate of symbols) of the UART.
Parameters
rate The new rate.
Returns
OK if no errors occurred.
Definition at line 85 of file uart.c.
References COM1_UART_ADDRESS, DLAB_OFF, DLAB_ON, GET_LSB, GET_MSB, UART_DLH, UART_DLL, uart_get_line_ctrl(), and uart_set_line_ctrl().
uart_set_interrupt_reg()
int() uart_set_interrupt_reg (__uint8_t ctrl)
Sets the IER register of the UART.
Returns
OK if no errors occurred.
Definition at line 80 of file uart.c.
References COM1_UART_ADDRESS, and UART_IER.
uart_set_line_ctrl()
int() uart_set_line_ctrl (__uint8_t ctrl)
Writes a control byte to the LCR register of the UART.
Parameters
ctrl The control byte.
Returns
OK if no errors occurred.
Definition at line 75 of file uart.c.
References COM1_UART_ADDRESS, and UART_LCR.
uart_subscribe_int()
int() uart_subscribe_int (__uint8_t * bit_no)
Subscribes to UART interrupts.
Parameters
[out] bit_no The bit number used.
Returns
OK if no errors occurred.
Definition at line 31 of file uart.c.
References COM1_UART_IRQ, and uart_subscribe_result.
uart_unsubscribe_int()
int() uart_unsubscribe_int ()
Unsubscribes from UART interrupts.
Returns
OK if no errors occurred.
Definition at line 55 of file uart.c.
References uart_subscribe_result.