OPERATION M.I.N.I.X.: RTC functions
RTC functions
Functions for using the RTC interface.
Functions
date_t * get_curr_date ()
Gets the current's date object.
void() reset_pie_state ()
Reset pie state.
int bcd_to_decimal (__uint8_t *val)
Converts a bcd number to decimal.
int binary_to_bcd (__uint8_t *val)
Converts a binary number to bcd mode.
int rtc_set_date (date_t *date)
Sets the date on a date_t object.
int() rtc_subscribe_int (__uint8_t *bit_no)
Subscribes to the interrupts of the rtc.
int() rtc_unsubscribe_int ()
Unsibscribes rtc interrupts.
int() rtc_int_cause (__uint8_t *cause)
Gets the cause of the interrupt.
int() enable_pie_int ()
Enables periodic interupts.
int() enable_aie_int ()
Enables alarm interrupts.
int() enable_uie_int ()
Enable update interrupts.
int() disable_pie_int ()
Enables periodic interupts.
int() disable_aie_int ()
Enables alarm interrupts.
int() disable_uie_int ()
Enable update interrupts.
int() rtc_set_alarm (__uint8_t sec, __uint8_t min, __uint8_t hour)
Enables an alarm interrupt.
int() rtc_set_periodic_500ms ()
Set periodic interrupts to 500ms.
int() rtc_reset_pie ()
Reset periodic interrupts value.
int() init_rtc_vars ()
Initializes variables to the minix configuration to restore it later.
int() reset_rtc ()
Resets rtc to minix default.
void rtc_ih (void)
RTC Interrupt handler.
Detailed Description
Functions for using the RTC interface.
Function Documentation
bcd_to_decimal()
int bcd_to_decimal (__uint8_t * val)
Converts a bcd number to decimal.
Parameters
[out] Input and ouput
Definition at line 30 of file rtc_controller.c.
binary_to_bcd()
int binary_to_bcd (__uint8_t * val)
Converts a binary number to bcd mode.
Parameters
[out] Input and output
Definition at line 42 of file rtc_controller.c.
disable_aie_int()
int() disable_aie_int ()
Enables alarm interrupts.
Definition at line 161 of file rtc_controller.c.
References RTC_AIE, rtc_read_reg(), RTC_REGISTER_B, and rtc_write_reg().
disable_pie_int()
int() disable_pie_int ()
Enables periodic interupts.
Definition at line 155 of file rtc_controller.c.
References RTC_PIE, rtc_read_reg(), RTC_REGISTER_B, and rtc_write_reg().
disable_uie_int()
int() disable_uie_int ()
Enable update interrupts.
Definition at line 167 of file rtc_controller.c.
References rtc_read_reg(), RTC_REGISTER_B, RTC_UIE, and rtc_write_reg().
enable_aie_int()
int() enable_aie_int ()
Enables alarm interrupts.
Definition at line 143 of file rtc_controller.c.
References RTC_AIE, rtc_read_reg(), RTC_REGISTER_B, and rtc_write_reg().
enable_pie_int()
int() enable_pie_int ()
Enables periodic interupts.
Definition at line 137 of file rtc_controller.c.
References RTC_PIE, rtc_read_reg(), RTC_REGISTER_B, and rtc_write_reg().
enable_uie_int()
int() enable_uie_int ()
Enable update interrupts.
Definition at line 149 of file rtc_controller.c.
References rtc_read_reg(), RTC_REGISTER_B, RTC_UIE, and rtc_write_reg().
get_curr_date()
date_t* get_curr_date ()
Gets the current's date object.
Definition at line 26 of file rtc_controller.c.
References curr_date.
init_rtc_vars()
int() init_rtc_vars ()
Initializes variables to the minix configuration to restore it later.
Definition at line 198 of file rtc_controller.c.
References config_a, config_b, rtc_read_reg(), RTC_REGISTER_A, and RTC_REGISTER_B.
reset_pie_state()
void() reset_pie_state ()
Reset pie state.
Definition at line 22 of file rtc_controller.c.
References pie_state.
reset_rtc()
int() reset_rtc ()
Resets rtc to minix default.
Definition at line 203 of file rtc_controller.c.
References config_a, RTC_REGISTER_A, and rtc_write_reg().
rtc_ih()
void rtc_ih (void)
RTC Interrupt handler.
Definition at line 208 of file rtc_controller.c.
References get_curr_date(), get_round_timer(), pie_state, RTC_AF, rtc_int_cause(), RTC_PF, rtc_set_date(), and RTC_UF.
rtc_int_cause()
int() rtc_int_cause (__uint8_t * cause)
Gets the cause of the interrupt.
Parameters
[out] cause Output value
Definition at line 130 of file rtc_controller.c.
References RTC_ADDR_REG, RTC_DATA_REG, RTC_REGISTER_C, and util_sys_inb().
rtc_reset_pie()
int() rtc_reset_pie ()
Reset periodic interrupts value.
Definition at line 180 of file rtc_controller.c.
References rtc_read_reg(), RTC_REGISTER_A, RTC_RS_CLEAR, and rtc_write_reg().
rtc_set_alarm()
int() rtc_set_alarm (__uint8_t sec, __uint8_t min, __uint8_t hour)
Enables an alarm interrupt.
Parameters
sec Seconds
min Minutes
hour Hours
Definition at line 187 of file rtc_controller.c.
References binary_to_bcd(), RTC_ALARM_HOURS, RTC_ALARM_MINUTES, RTC_ALARM_SECONDS, RTC_DONT_CARE, and rtc_write_reg().
rtc_set_date()
int rtc_set_date (date_t * date)
Sets the date on a date_t object.
Parameters
[out] date_t object to fill
Definition at line 80 of file rtc_controller.c.
References bcd_to_decimal(), date::day, date::hour, date::min, date::month, reset_rtc(), RTC_HOURS, RTC_MINUTES, RTC_MONTH, RTC_MONTH_DAY, rtc_read_reg(), RTC_REGISTER_A, RTC_SECONDS, RTC_UIP, rtc_write_reg(), RTC_YEAR, date::sec, and date::year.
rtc_set_periodic_500ms()
int() rtc_set_periodic_500ms ()
Set periodic interrupts to 500ms.
Definition at line 173 of file rtc_controller.c.
References rtc_read_reg(), RTC_REGISTER_A, RTC_RS0, RTC_RS1, RTC_RS2, RTC_RS3, and rtc_write_reg().
rtc_subscribe_int()
int() rtc_subscribe_int (__uint8_t * bit_no)
Subscribes to the interrupts of the rtc.
Parameters
[out] Bit number chosen
Definition at line 118 of file rtc_controller.c.
References RTC_IRQ, and rtc_subscribe.
rtc_unsubscribe_int()
int() rtc_unsubscribe_int ()
Unsibscribes rtc interrupts.
Definition at line 124 of file rtc_controller.c.
References rtc_subscribe.