OPERATION M.I.N.I.X.: Game Manager
Game Manager
Functions that change the state of the game.
Macros
#define ROUND_TIMER 160
Typedefs
typedef enum game_state game_state_t
The different game states.
Enumerations
enum game_state {
MAIN_MENU, MP_MENU, GAME, MP_GAME,
DEAD_MENU, NEXT_LVL_MENU, END_S_GAME, END_M_GAME,
WIN_GAME, LOSE_GAME, DISCONNECT, EXIT
}
The different game states.
Functions
game_state_t get_state ()
Gets the current game state.
int * get_round_timer ()
Returns memory addres of round timer.
int gm_init_game (int map_num, int game_mode, int player)
Starts the game loop.
void gm_reset_mp_game ()
Closes the multi player game.
void update_game_state ()
Updates the game state based on actions made by the players.
void set_state (game_state_t state)
Sets the game state.
void() game_handler ()
Handles the game's functions and changes the game's state according to input and current state.
void() interrupt_handler (__uint8_t mouse_bit_no, __uint8_t kb_bit_no, __uint8_t timer_bit_no, __uint8_t uart_bit_no, __uint8_t rtc_bit_no)
Handles interrupts and is essentially the main game loop.
Variables
static game_state_t state
The current game state.
Detailed Description
Functions that change the state of the game.
Macro Definition Documentation
ROUND_TIMER
#define ROUND_TIMER 160
Definition at line 13 of file game_manager.h.
Typedef Documentation
game_state_t
typedef enum game_state game_state_t
The different game states.
Enumeration Type Documentation
game_state
enum game_state
The different game states.
Enumerator
MAIN_MENU
Game is in the main menu.
MP_MENU
Game is in the multi player screen (waiting for connection).
GAME
Game is running in the single player mode.
MP_GAME
Game is running in the multi player mode.
DEAD_MENU
Game is in the Lose/Win screen.
NEXT_LVL_MENU
Game is in the Next level/Single player win screen.
END_S_GAME
A request to end the single player game has been made.
END_M_GAME
A request to end the multi player game has been made.
WIN_GAME
Game is in the win screen.
LOSE_GAME
Game is in the lose screen.
DISCONNECT
The other player in multi player mode has disconnected.
EXIT
A request to close the game has been made.
Definition at line 17 of file game_manager.h.
Function Documentation
game_handler()
void() game_handler ()
Handles the game's functions and changes the game's state according to input and current state.
Definition at line 118 of file game_manager.c.
References bot_int_ih(), CLEANUP, CONNECTED, DISCONNECT, DISCONNECTED, display(), enemies, GAME, get_network_player(), get_network_state(), get_state(), gm_reset_mp_game(), handle_enemies(), INIT, load_level(), LOSE_GAME, LOSE_GAME_ERR, MAIN_MENU, MP_GAME, MP_MENU, player, player_int_ih(), reset_player_mouse_movm(), set_network_state(), set_state(), state, time_counter, uart_receive_data(), uart_send_data(), uart_sync(), update_game_state(), update_pickups(), WIN_GAME, and WIN_GAME_ERR.
get_round_timer()
int* get_round_timer ()
Returns memory addres of round timer.
Returns
round timer
Definition at line 32 of file game_manager.c.
References game_timer.
get_state()
game_state_t get_state ()
Gets the current game state.
Returns
The current game state.
Definition at line 28 of file game_manager.c.
References state.
gm_init_game()
int gm_init_game (int map_num, int game_mode, int player)
Starts the game loop.
Allocates all needed memory and loads in everything.
Parameters
map_num The number of the map being loaded.
game_mode The mode (single player – 1, multi player – 2)
player The number of the player who is playing.
Returns
Definition at line 44 of file game_manager.c.
References disable_uie_int(), enable_pie_int(), GAME, game_timer, load_level(), player, reset_pie_state(), ROUND_TIMER, rtc_set_periodic_500ms(), and set_state().
gm_reset_mp_game()
void gm_reset_mp_game ()
Closes the multi player game.
Frees all possible memory used up.
Definition at line 61 of file game_manager.c.
References CLEANUP, free_level(), init_player_ctrls(), and set_network_state().
interrupt_handler()
void() interrupt_handler (__uint8_t mouse_bit_no, __uint8_t kb_bit_no, __uint8_t timer_bit_no, __uint8_t uart_bit_no, __uint8_t rtc_bit_no)
Handles interrupts and is essentially the main game loop.
Parameters
mouse_bit_no Timer interrupt bit number.
kb_bit_no Mouse interrupt bit number.
timer_bit_no Keyboard interrupt bit number.
uart_bit_no UART interrupt bit number.
rtc_bit_no RTC interrupt bit number.
Definition at line 158 of file game_manager.c.
References BIT, BREAKCODE_ESC, EXIT, game_handler(), get_state(), handle_kbd_evt(), handle_mouse_evt(), last_kb_byte, rtc_ih(), timer_int_handler(), and uart_ih().
set_state()
void set_state (game_state_t state)
Sets the game state.
Parameters
state The new game state.
Definition at line 36 of file game_manager.c.
References enable_uie_int(), MAIN_MENU, and state.
update_game_state()
void update_game_state ()
Updates the game state based on actions made by the players.
Definition at line 67 of file game_manager.c.
References END_M_GAME, END_S_GAME, free_level(), GAME, get_mp_enemy_player(), get_player(), get_round_timer(), gm_reset_mp_game(), init_player_ctrls(), LOSE_GAME, MAIN_MENU, map::matrix, MP_GAME, player_info::position, set_state(), state, UART_LOSE_GAME, uart_send_string(), UART_WIN_GAME, WIN_GAME, vector::x, and vector::y.
Variable Documentation
state
game_state_t state static
The current game state.
Definition at line 45 of file game_manager.h.