OPERATION M.I.N.I.X.: Level Loader
Level Loader
Functions to properly handle the game's memory while loading levels, games, and sprites.
Macros
#define LAST_LVL 2
Functions
__int8_t get_curr_lvl ()
Returns level number to identify in the menu if there is a next level or not The value -1 represents multiplayer.
int() init_game (__uint8_t *t_bit_no, __uint8_t *ms_bit_no, __uint8_t *kb_bit_no, __uint8_t *uart_bit_no, __uint8_t *rtc_bit_no)
Load modules of the game from the lib and initializes everything.
int() load_level (int num_map, int mode, int player)
Loads a specified level.
int() setup_multiplayer (int player)
Setups multiplayer game mode and level.
int free_level ()
Free memory allocated by load level and setup_game_x.
void setup_game_2 ()
Setup level 2.
int free_game ()
Free the memory allocated by load_game.
Detailed Description
Functions to properly handle the game's memory while loading levels, games, and sprites.
Macro Definition Documentation
LAST_LVL
#define LAST_LVL 2
Identifies the last single player level
Definition at line 14 of file level_manager.h.
Function Documentation
free_game()
int free_game ()
Free the memory allocated by load_game.
Definition at line 439 of file level_manager.c.
References free_sprites(), free_uart_queues(), kb_unsubscribe_int(), kbc_disable_int(), kbc_enable_int(), mouse_unsubscribe_int(), ms_set_default(), reset_cmd_byte(), reset_rtc(), reset_to_text_mode(), rtc_unsubscribe_int(), and timer_unsubscribe_int().
free_level()
int free_level ()
Free memory allocated by load level and setup_game_x.
Returns
Error code
Definition at line 425 of file level_manager.c.
References close_map(), disable_pie_int(), free_collision_table(), free_controllers(), free_gun_anims(), free_pickups(), free_players(), gun_instance::gun, player_info::guns, player, and rtc_reset_pie().
get_curr_lvl()
__int8_t get_curr_lvl ()
Returns level number to identify in the menu if there is a next level or not The value -1 represents multiplayer.
Returns
curr_lvl
Definition at line 33 of file level_manager.c.
References curr_lvl.
init_game()
int() init_game (__uint8_t * t_bit_no, __uint8_t * ms_bit_no, __uint8_t * kb_bit_no, __uint8_t * uart_bit_no, __uint8_t * rtc_bit_no)
Load modules of the game from the lib and initializes everything.
Parameters
t_bit_no Timer interrupt bit number.
ms_bit_no Mouse interrupt bit number.
kb_bit_no Keyboard interrupt bit number.
uart_bit_no UART interrupt bit number.
rtc_bit_no RTC interrupt bit number.
Returns
OK if no errors occurred.
Definition at line 257 of file level_manager.c.
References BAUD_115200, BITS_PER_CHAR, ENABLE_LINE_STATUS, enable_ms(), ENABLE_RECEIVE, enable_stream(), ENABLE_TRANSMIT, enable_uie_int(), init_player_ctrls(), init_rtc_vars(), init_settings(), init_uart_queues(), kb_subscribe_int(), kbc_disable_int(), kbc_enable_int(), kbc_ih(), load_sprites(), MAIN_MENU, MODE, mouse_subscribe_int(), ODD_PARITY, reset_to_text_mode(), rtc_ih(), rtc_subscribe_int(), SET_RESOLUTION, SET_SAMPLE_RATE, set_state(), timer_subscribe_int(), uart_ih(), uart_init_fifo(), uart_set_baud_rate(), uart_set_interrupt_reg(), uart_set_line_ctrl(), uart_subscribe_int(), vg_init(), and write_ms_cmd().
load_level()
int() load_level (int num_map, int mode, int player)
Loads a specified level.
Parameters
num_map The number of the map to load.
mode The game mode.
player Player 1 or player 2.
Returns
Error code.
Definition at line 333 of file level_manager.c.
References map::columns, curr_lvl, init_collision_table(), init_guns(), map::lines, load_map(), player, setup_game_1(), setup_game_2(), and setup_multiplayer().
setup_game_2()
void setup_game_2 ()
Setup level 2.
Definition at line 84 of file level_manager.c.
References add_ammo(), add_armor(), add_medkit(), BOT, create_gun_instance(), enemies, GAME, init_enemy(), init_player(), player, PLAYER, set_state(), switch_gun(), vector::x, and vector::y.
setup_multiplayer()
int() setup_multiplayer (int player)
Setups multiplayer game mode and level.
Parameters
player The player number.
Definition at line 367 of file level_manager.c.
References add_ammo(), add_armor(), create_gun_instance(), init_player(), MP_GAME, NETWORK_PLAYER, player, PLAYER, set_state(), vector::x, and vector::y.