OPERATION M.I.N.I.X.: Player
Player
Functions to do operations related to player.
Data Structures
struct player_info
Macros
#define PLAYER_SPEED 0.05
Enumerated type for specifying the timer value initialization.
#define STRAFE_SPEED 0.025
Typedefs
typedef enum player_type player_type_t
Enum that identifies types of players to choose the controls.
typedef struct player_info player_info_t
Enumerations
enum player_type { PLAYER, NETWORK_PLAYER, BOT }
Enum that identifies types of players to choose the controls.
Functions
player_info_t * get_player ()
Returns player's 1 pointer.
player_info_t * get_mp_enemy_player ()
Returns player's 2 (mulitplayer) pointer.
void init_player_ctrls ()
Initializes player controls to use in menus.
int() reset_player_mouse_movm (player_info_t *ply)
Reset player's mouse desl to 0.
int() init_player_anims (player_info_t *p)
Initializes player animations.
int() free_player_anims (player_info_t *p)
Frees the memory allocated by init_player_anims()
void init_player (player_type_t type, vector_t *position, vector_t *direction, double radius, int health, int max_health, int armor, int max_armor, gun_instance_t *instances, int num_guns)
Function to construct a player or bot.
void free_players ()
Frees the memory allocated by init_player.
_Bool() hit_player (double *dist, player_info_t *p1, player_info_t *p2)
Verifies if the second player was hit by a shot taken by p1 Calculates tangent points of p2 and verifies direction of p1 and checks if its within bounds of those thangent lines.
void() player_int_ih (player_info_t *ply)
Player int handler Analyses controls and moves, shoots and select animations that should be played according to them.
void() bot_int_ih ()
Handle bots events.
void() switch_gun (player_info_t *ply, int index)
Function to switch the gun.
Detailed Description
Functions to do operations related to player.
Macro Definition Documentation
PLAYER_SPEED
#define PLAYER_SPEED 0.05
Enumerated type for specifying the timer value initialization.
Definition at line 23 of file player.h.
STRAFE_SPEED
#define STRAFE_SPEED 0.025
Definition at line 24 of file player.h.
Typedef Documentation
player_info_t
typedef struct player_info player_info_t
player_type_t
typedef enum player_type player_type_t
Enum that identifies types of players to choose the controls.
Enumeration Type Documentation
player_type
enum player_type
Enum that identifies types of players to choose the controls.
Enumerator
PLAYER
Normal controlled player.
NETWORK_PLAYER
Player controlled by network.
BOT
Player controlled by the system.
Definition at line 29 of file player.h.
Function Documentation
bot_int_ih()
void() bot_int_ih ()
Handle bots events.
Definition at line 525 of file player.c.
References enemies, num_enemies, and player_int_ih().
free_player_anims()
int() free_player_anims (player_info_t * p)
Frees the memory allocated by init_player_anims()
Parameters
p The player
Definition at line 150 of file player.c.
free_players()
void free_players ()
Frees the memory allocated by init_player.
Definition at line 218 of file player.c.
References enemies, guns, player_info::guns, num_enemies, and player.
get_mp_enemy_player()
player_info_t* get_mp_enemy_player ()
Returns player's 2 (mulitplayer) pointer.
Returns
pointer to player 2
Definition at line 32 of file player.c.
References enemies.
get_player()
player_info_t* get_player ()
Returns player's 1 pointer.
Returns
pointer to player
Definition at line 28 of file player.c.
References player.
hit_player()
_Bool() hit_player (double * dist, player_info_t * p1, player_info_t * p2)
Verifies if the second player was hit by a shot taken by p1 Calculates tangent points of p2 and verifies direction of p1 and checks if its within bounds of those thangent lines.
Parameters
dist [out] If p2 was hit, returns the distance of the player
p1 Player who shot the gun
p2 Player to check if was shot
Definition at line 254 of file player.c.
References abs_double(), degree(), normalize(), vec_mag(), vector::x, and vector::y.
init_player()
void init_player (player_type_t type, vector_t * position, vector_t * direction, double radius, int health, int max_health, int armor, int max_armor, gun_instance_t * instances, int num_guns)
Function to construct a player or bot.
Parameters
type Whether it is a bot or a player
position Starting position in the map
direction Starting look direction
radius Radius of the player's collider
health Health of the player
max_health Maximum health of the player
armor Armor of the player
max_armor Maximum armor of the player
num_guns Number of weapons in the inventory
guns Guns to add to inventory
Definition at line 165 of file player.c.
References player_info::armor, BOT, player_info::camera_plane, gun::cooldown_time, player_info::direction, enemies, gun_instance::gun, player_info::gun_index, player_info::guns, player_info::health, init_player_anims(), INITIAL, player_info::inventory_size, KEY_UP, player_info::max_armor, player_info::max_health, controls_t::mouse_state, player_info::movm, normalize(), num_enemies, player, PLAYER, player_info::position, player_info::radius, gun::range, retrieve_settings(), player_info::should_render, gun_instance::state, player_info::type, vector::x, and vector::y.
init_player_anims()
int() init_player_anims (player_info_t * p)
Initializes player animations.
Parameters
p The player
Idle animation
Crouch animation
Walk and run animations
Fire animation
Definition at line 36 of file player.c.
References animated_sprite::cur_frame, animated_sprite::frames, animated_sprite::frames_per_sprite, animated_sprite::num_fig, animated_sprite::sprite, and player_info::sprites.
init_player_ctrls()
void init_player_ctrls ()
Initializes player controls to use in menus.
Definition at line 161 of file player.c.
References player_info::movm, and player.
player_int_ih()
void() player_int_ih (player_info_t * ply)
Player int handler Analyses controls and moves, shoots and select animations that should be played according to them.
Parameters
ply Player to affect the changes
Definition at line 399 of file player.c.
References gun::automatic, BOT, player_info::camera_plane, check_player_pickup_collision(), CLOSED, kbd_ctrl_state::crouch, player_info::curr_anim, player_info::direction, fire(), GAME, get_inv_menu_state(), get_state(), gun_instance::gun, player_info::gun_index, player_info::guns, player_info::health, idx, controls_t::kbd_state, controls_t::lb_held_down, controls_t::lb_single_tap, controls_t::mouse_desl, controls_t::movement, player_info::movm, MP_GAME, NETWORK_PLAYER, kbd_ctrl_state::nums_press, pickup_index(), PLAYER, PLAYER_SPEED, player_wall_collision(), player_info::position, PROGRESS, player_info::should_render, kbd_ctrl_state::sprint, player_info::sprites, animated_sprite::state, STRAFE_SPEED, switch_gun(), player_info::type, update_anim(), update_gun_state(), update_player_controls(), vector::x, kbd_ctrl_state::x_neg, kbd_ctrl_state::x_pos, vector::y, kbd_ctrl_state::y_neg, and kbd_ctrl_state::y_pos.
reset_player_mouse_movm()
int() reset_player_mouse_movm (player_info_t * ply)
Reset player's mouse desl to 0.
Parameters
ply Player to apply
Definition at line 23 of file player.c.
switch_gun()
void() switch_gun (player_info_t * ply, int index)
Function to switch the gun.
Parameters
ply Current player
index The index of the weapon (0 to 2)
Definition at line 285 of file player.c.
References player_info::gun_index, player_info::guns, INITIAL, INVENTORY, and gun_instance::state.