OPERATION M.I.N.I.X.: Pickups
Pickups
Functions used to handle pickups.
Data Structures
struct collision_list
Represents a list of collisions (of pickups) in a certain position of a map.
struct collision_table
Collision table.
struct pickup_vtable
Struct that represents a virtual table with 'virtual'-like functions.
struct pickup
Base class for pickups, has a virtual table for calling functions for different types of pickups.
struct ammo
struct that represents the ammo pickups.
struct medkit
Medkit struct.
struct armor
Armor stuct.
Macros
#define COLLISION_LIST_ALLOC_STEP 5
Typedefs
typedef struct collision_list collision_list_t
Represents a list of collisions (of pickups) in a certain position of a map.
typedef collision_list_t * collision_line_t
Line of a collision table.
typedef struct collision_table collision_table_t
Collision table.
typedef struct pickup_vtable pickup_vtable_t
Struct that represents a virtual table with 'virtual'-like functions.
typedef struct pickup pickup_t
Base class for pickups, has a virtual table for calling functions for different types of pickups.
typedef struct ammo ammo_t
struct that represents the ammo pickups.
typedef struct medkit medkit_t
Medkit struct.
typedef struct armor armor_t
Armor stuct.
Functions
static _Bool pickup_handler (player_info_t *player, pickup_t *pickup)
Function wrapper for calling a pickup handler based on its type using the chosen virtual table.
size_t add_ammo (vector_t *position, double radius, __uint16_t ammo_index, __uint16_t packets)
Adds ammo to the pickups.
size_t add_medkit (vector_t *position, double radius, __uint16_t health)
Adds medkit to the pickups.
void() update_pickups ()
Updates pickup animations.
size_t add_armor (vector_t *position, double radius, __uint16_t armor_quantity)
Adds armor to the pickups.
int init_collision_table (size_t width, size_t height)
Initializes the pickup collision table.
void free_collision_table ()
Frees resources used up by the collision table.
void print_table ()
size_t check_player_pickup_collision (player_info_t *player)
Checks if a player can pick up an item.
_Bool pickup_index (player_info_t *player, unsigned index)
Picks up an item with a given index.
size_t add_pickup (pickup_t *pickup)
Adds pickup to pickup array and sets its position in the collision table.
pickup_t get_pickup (unsigned index)
Gets a copy of a pickup from the pickup array given its index.
size_t() get_pickups_size ()
Gets the number of pickups + 1.
void delete_pickup (unsigned index)
Removes a pickup from the collision table and ignores it in the pickup array.
void free_pickups ()
Frees resources used up by the pickup array.
Variables
pickup_vtable_t AMMO []
Gathers all possible virtual tables to be used in other files.
pickup_vtable_t MEDKIT []
pickup_vtable_t ARMOR []
Detailed Description
Functions used to handle pickups.
Macro Definition Documentation
COLLISION_LIST_ALLOC_STEP
#define COLLISION_LIST_ALLOC_STEP 5
Definition at line 15 of file pickups.h.
Typedef Documentation
ammo_t
typedef struct ammo ammo_t
struct that represents the ammo pickups.
armor_t
typedef struct armor armor_t
Armor stuct.
collision_line_t
typedef collision_list_t* collision_line_t
Line of a collision table.
Definition at line 32 of file pickups.h.
collision_list_t
typedef struct collision_list collision_list_t
Represents a list of collisions (of pickups) in a certain position of a map.
collision_table_t
typedef struct collision_table collision_table_t
Collision table.
medkit_t
typedef struct medkit medkit_t
Medkit struct.
pickup_t
typedef struct pickup pickup_t
Base class for pickups, has a virtual table for calling functions for different types of pickups.
pickup_vtable_t
typedef struct pickup_vtable pickup_vtable_t
Struct that represents a virtual table with 'virtual'-like functions.
Function Documentation
add_ammo()
size_t add_ammo (vector_t * position, double radius, __uint16_t ammo_index, __uint16_t packets)
Adds ammo to the pickups.
Parameters
position pointer to position in map
radius collider radius of pickup
ammo_index the type of ammo
packets ammount of packets added
Returns
returns the index of the pickup.
Definition at line 83 of file pickups.c.
References add_pickup(), AMMO, ammo::ammo_index, circle::center, pickup::collider, init_ammo_anims(), ammo::packets, pickup::picked_up, pickup::pickup_details, circle::radius, and pickup::vtable.
add_armor()
size_t add_armor (vector_t * position, double radius, __uint16_t armor_quantity)
Adds armor to the pickups.
Parameters
position pointer to position in map
radius collider radius of pickup
armor_quantity quantity of armor added.
Returns
returns the index of the pickup.
Definition at line 156 of file pickups.c.
References add_pickup(), ARMOR, armor::armor, circle::center, pickup::collider, init_armor_anims(), pickup::picked_up, pickup::pickup_details, circle::radius, and pickup::vtable.
add_medkit()
size_t add_medkit (vector_t * position, double radius, __uint16_t health)
Adds medkit to the pickups.
Parameters
position pointer to position in map
radius collider radius of pickup
health health added.
Returns
returns the index of the pickup.
Definition at line 120 of file pickups.c.
References add_pickup(), circle::center, pickup::collider, medkit::health, init_medi_anims(), MEDKIT, pickup::picked_up, pickup::pickup_details, circle::radius, and pickup::vtable.
add_pickup()
size_t add_pickup (pickup_t * pickup)
Adds pickup to pickup array and sets its position in the collision table.
Parameters
pickup the pickup being added
Returns
returns the index of the pickup
Definition at line 312 of file pickups.c.
References add_collision(), pickup::picked_up, pickups, and pickups_size.
check_player_pickup_collision()
size_t check_player_pickup_collision (player_info_t * player)
Checks if a player can pick up an item.
Parameters
player pointer to a player structure
Returns
returns the index of the closest pickup
Definition at line 272 of file pickups.c.
References circle::center, pickup::collider, dist_positions_squared(), collision_table::height, collision_list::indexes, collision_list::num_of_indexes, pickup_index(), pickups, player, player_info::position, circle::radius, collision_table::table, collision_table::width, vector::x, coordinate::x, vector::y, and coordinate::y.
delete_pickup()
void delete_pickup (unsigned index)
Removes a pickup from the collision table and ignores it in the pickup array.
Parameters
index index of the pickup
Definition at line 359 of file pickups.c.
References circle::center, pickup::collider, pickup::picked_up, pickups, pickups_size, and remove_collision().
free_collision_table()
void free_collision_table ()
Frees resources used up by the collision table.
Definition at line 197 of file pickups.c.
References collision_table::height, collision_list::indexes, collision_table::table, and collision_table::width.
free_pickups()
void free_pickups ()
Frees resources used up by the pickup array.
Definition at line 368 of file pickups.c.
References idx, pickups, and pickups_size.
get_pickup()
pickup_t get_pickup (unsigned index)
Gets a copy of a pickup from the pickup array given its index.
Parameters
index index of the pickup
Returns
returns the pickup with that index or a dummy pickup, if it does not exist.
Definition at line 344 of file pickups.c.
References pickup::picked_up, pickups, and pickups_size.
get_pickups_size()
size_t() get_pickups_size ()
Gets the number of pickups + 1.
Returns
returns the number of pickups + 1.
Definition at line 355 of file pickups.c.
References pickups_size.
init_collision_table()
int init_collision_table (size_t width, size_t height)
Initializes the pickup collision table.
Parameters
width width of the map
height height of the map
Returns
0 if ok, non-zero if not.
Definition at line 172 of file pickups.c.
References BAD_ALLOC, collision_table::height, collision_list::indexes, collision_list::max_indexes, collision_list::num_of_indexes, collision_table::table, and collision_table::width.
pickup_handler()
static _Bool pickup_handler (player_info_t * player, pickup_t * pickup) static
Function wrapper for calling a pickup handler based on its type using the chosen virtual table.
Parameters
pickup the item being picked up
player the player picking up the item
Returns
returns true if item was picked up, false if item was not picked up
Definition at line 108 of file pickups.h.
References pickup_vtable::handler, pickup::pickup_details, player, and pickup::vtable.
pickup_index()
_Bool pickup_index (player_info_t * player, unsigned index)
Picks up an item with a given index.
Parameters
player pointer to a player structure
index pickup index
Returns
returns true if picked up
Definition at line 336 of file pickups.c.
References delete_pickup(), pickup_handler(), pickups, and player.
print_table()
void print_table ()
Definition at line 297 of file pickups.c.
References collision_table::height, idx, collision_list::indexes, collision_list::num_of_indexes, collision_table::table, and collision_table::width.
update_pickups()
void() update_pickups ()
Updates pickup animations.
Definition at line 191 of file pickups.c.
References idx, pickups, pickups_size, and update_anim().
Variable Documentation
AMMO
pickup_vtable_t AMMO[] extern
Gathers all possible virtual tables to be used in other files.
Gathers all possible virtual tables to be used in other files.
Definition at line 81 of file pickups.c.
ARMOR
pickup_vtable_t ARMOR[]
Definition at line 115 of file pickups.h.
MEDKIT
pickup_vtable_t MEDKIT[]
Definition at line 115 of file pickups.h.