OPERATION M.I.N.I.X.: Queue
Queue
Functions to use with queue object.
Typedefs
typedef struct queue queue_t
Queue structure using a linked list.
Functions
queue_t *() queue_init ()
Creates a queue structure.
void() queue_push (queue_t *queue, __int16_t byte)
Adds an element to the back of the given queue.
__int16_t() queue_front (queue_t *queue)
Gets the element at the front of the given queue.
void() queue_pop (queue_t *queue)
Removes the element at the front of the given queue.
_Bool() queue_empty (queue_t *queue)
Checks if the given queue is empty.
void() queue_delete (queue_t *queue)
Frees memory allocated by the given queue's items, and the queue itself.
void() queue_clean (queue_t *queue)
Cleans the queue, removing and freeing all of its elements.
Detailed Description
Functions to use with queue object.
Typedef Documentation
queue_t
typedef struct queue queue_t
Queue structure using a linked list.
Definition at line 1 of file queue.h.
Function Documentation
queue_clean()
void() queue_clean (queue_t * queue)
Cleans the queue, removing and freeing all of its elements.
Parameters
queue Queue to apply the operation
Definition at line 74 of file queue.c.
References queue_empty(), and queue_pop().
queue_delete()
void() queue_delete (queue_t * queue)
Frees memory allocated by the given queue's items, and the queue itself.
Parameters
queue The given queue.
Definition at line 66 of file queue.c.
References queue_empty(), and queue_pop().
queue_empty()
_Bool() queue_empty (queue_t * queue)
Checks if the given queue is empty.
Parameters
queue The given queue.
Returns
True if the queue is empty, false otherwise.
Definition at line 62 of file queue.c.
References front.
queue_front()
__int16_t() queue_front (queue_t * queue)
Gets the element at the front of the given queue.
Parameters
queue The given queue.
Returns
The element at the front.
Definition at line 49 of file queue.c.
References queue_item::byte, and front.
queue_init()
queue_t*() queue_init ()
Creates a queue structure.
Returns
The pointer to the queue structure created.
Definition at line 25 of file queue.c.
References back, and front.
queue_pop()
void() queue_pop (queue_t * queue)
Removes the element at the front of the given queue.
Parameters
queue The given queue.
Definition at line 54 of file queue.c.
References front, and queue_item::next.
queue_push()
void() queue_push (queue_t * queue, __int16_t byte)
Adds an element to the back of the given queue.
Parameters
queue The given queue.
byte The element to be added.
Definition at line 34 of file queue.c.
References back, queue_item::byte, front, and queue_item::next.