OPERATION M.I.N.I.X.: Rendering Functions
Rendering Functions
Functions used to render the game's objects.
Data Structures
struct render
Macros
#define CROSSHAIR_SIZE 50
#define CROSSHAIR_SIDE 5
#define CROSSHAIR_SPACE 5
#define CROSSHAIR_COLOR 0XFF0000
Typedefs
typedef struct render render_t
Functions
int() display_map (double range)
Renders the currently loaded map using the ray casting render technique.
int() render_crosshair ()
Function to render a red crosshair The crosshair is always placed in the center of the screen according to the values specified.
int() render_player (player_info_t *p1, player_info_t *p2, double range, render_t *render, render_t *health_render, render_t *armor_render)
Renders a player on the screen.
void() draw_mouse ()
Draws the mouse.
void render_number (int value, pair_t *pos, int max_digits)
Function to render a number.
void render_time_number (int value, pair_t *pos, int max_digits)
Function to render a number filling the initial gaps with 0.
int display (double range)
General function that renders the screen Chooses what to render based on the state of the game.
Detailed Description
Functions used to render the game's objects.
Macro Definition Documentation
CROSSHAIR_COLOR
#define CROSSHAIR_COLOR 0XFF0000
Definition at line 18 of file render.h.
CROSSHAIR_SIDE
#define CROSSHAIR_SIDE 5
Definition at line 16 of file render.h.
CROSSHAIR_SIZE
#define CROSSHAIR_SIZE 50
Definition at line 15 of file render.h.
CROSSHAIR_SPACE
#define CROSSHAIR_SPACE 5
Definition at line 17 of file render.h.
Typedef Documentation
render_t
typedef struct render render_t
Function Documentation
display()
int display (double range)
General function that renders the screen Chooses what to render based on the state of the game.
Definition at line 644 of file render.c.
References DISCONNECT, GAME, get_state(), LOSE_GAME, MAIN_MENU, MP_GAME, MP_MENU, put_buffer(), render_disconnect_screen(), render_game(), render_menu(), render_mp_menu(), render_win_lose_screen(), and WIN_GAME.
display_map()
int() display_map (double range)
Renders the currently loaded map using the ray casting render technique.
The map is rendered by projecting walls into an imaginary camera plane in front of the player, perpendicular to the player's direction.
This is done by shooting rays from each of the screens' columns and determining if it hits a wall (can be adjusted with the range parameter).
If it hits a wall, it calculates the perpendicular distance from the camera plane to the wall and calculates the height to be drawn by dividing a constant by the perpendicular distance. In this specific case, the constant chosen was the height (or vertical resolution) of the screen. (source and more details: https://lodev.org/cgtutor/raycasting.html)
(FIRST APPROACH) To draw the columns, an auxiliary buffer is used that is rotated by 90 degrees, making it so columns are drawn horizontally. This greatly increases performance as it reduces the number of cache misses, since the elements of the columns are now stored one after the other (contiguously) in cache. However, the downside is that this buffer later needs to be transposed.
(SECOND APPROACH (current)) All columns are stored in a simple data structure that stores it's starting position, ending position, texture index used and last color used. To allow for better cache optimization, these columns are drawn bit by bit in each horizontal line (scan line effect).
A range parameter is given, which defines the range the player can see and appropriately darkens textures to give a darkness effect, or like the player is holding a sphere of light.
Parameters
range the range the player can see (in blocks), 0 if player can see forever.
Returns
0 if returns ok.
Definition at line 459 of file render.c.
References player_info::camera_plane, clear_screen(), line_tex::darken, line_tex::darken_factor, player_info::direction, line::dist, ray_hit::distance, line::draw_higher, line::draw_lower, draw_walls(), g_data, graphics_data::h_res, ray_hit::hit, line_tex::last_tex_y, graphics_data::lines, ray_hit::map_pos, map::matrix, MAX_SPRITE_HEIGHT, MAX_SPRITE_WIDTH, player, player_info::position, shoot_ray(), line_tex::side, ray_hit::side, START_DARKEN, line_tex::step, line_tex::tex, line_tex::tex_hit_x, line_tex::tex_y, line::texture, graphics_data::v_res, vector::x, coordinate::x, vector::y, and coordinate::y.
draw_mouse()
void() draw_mouse ()
Draws the mouse.
Definition at line 637 of file render.c.
References draw_sprite_color_mask(), controls_t::mouse_pos, player_info::movm, player, retrieve_settings(), vector::x, pair::x, vector::y, and pair::y.
render_crosshair()
int() render_crosshair ()
Function to render a red crosshair The crosshair is always placed in the center of the screen according to the values specified.
Definition at line 80 of file render.c.
References CROSSHAIR_COLOR, CROSSHAIR_SIDE, CROSSHAIR_SIZE, CROSSHAIR_SPACE, draw_rect(), g_data, graphics_data::h_res, and graphics_data::v_res.
render_number()
void render_number (int value, pair_t * pos, int max_digits)
Function to render a number.
Parameters
value Number to render
pos Initial position
max_digits Max digits to render - Truncates the first digits
Definition at line 32 of file render.c.
References digitize(), draw_sprite(), sprite::texture_size, coordinate::x, and pair::x.
render_player()
int() render_player (player_info_t * p1, player_info_t * p2, double range, render_t * render, render_t * health_render, render_t * armor_render)
Renders a player on the screen.
Displays a sprite/animation from a set of 8 to create a 3D illusion depending on the direction of both players. Adapted from the following tutorial: https://lodev.org/cgtutor/raycasting3.html
Does not allow for players to be drawn behind walls and darkens sprite if far away. This is possible because we store the distances to the walls and compare the distance of the other player. If the distance to the player is smaller than a wall, we draw the corresponding vertical line
The second player is darkened by a factor calculated with the distance between both players
Above the player a health bar is also rendered according to the remaining health of the second player
Parameters
p1 pointer to the player
p2 pointer to the player to be drawn
range the range the player can be seen (in blocks), 0 if can always be seen
player_render Render object of player to be filled
health_render Render object of health bar
armor_render Render object of armor bar
Returns
0 if returns ok
Definition at line 228 of file render.c.
References degree(), g_data, graphics_data::h_res, idx, player_info::position, render_object(), graphics_data::v_res, vector::x, pair::x, vector::y, and pair::y.
render_time_number()
void render_time_number (int value, pair_t * pos, int max_digits)
Function to render a number filling the initial gaps with 0.
Parameters
value Number to render
pos Initial position
max_digits Max digits to render - Truncates the first digits
Definition at line 59 of file render.c.
References digitize(), draw_sprite(), sprite::texture_size, coordinate::x, and pair::x.