OPERATION M.I.N.I.X.: timer
timer
Functions for using the i8254 timers.
Data Structures
union timer_status_field_val
Union for storing values of timer status fields, including the full status byte.
Enumerations
enum timer_init { INVAL_val, LSB_only, MSB_only, MSB_after_LSB }
Enumerated type for specifying the timer value initialization.
enum timer_status_field { tsf_all, tsf_initial, tsf_mode, tsf_base }
Enumerated type for identifying the timer status fields.
Functions
int() timer_set_frequency (__uint8_t timer, __uint32_t freq)
Changes the operating frequency of a timer.
int() timer_subscribe_int (__uint8_t *bit_no)
Subscribes and enables Timer 0 interrupts.
int() timer_unsubscribe_int ()
Unsubscribes Timer 0 interrupts.
void() timer_int_handler ()
Timer 0 interrupt handler.
int() timer_get_conf (__uint8_t timer, __uint8_t *st)
Reads the input timer configuration (status) via read-back command.
int() timer_display_conf (__uint8_t timer, __uint8_t st, enum timer_status_field field)
Shows timer configuration.
int() timer_print_config (__uint8_t timer, enum timer_status_field field, union timer_status_field_val val)
Prints a timer config field value.
__uint32_t() timer_print_elapsed_time ()
Increments elapsed time count.
Detailed Description
Functions for using the i8254 timers.
Enumeration Type Documentation
timer_init
enum timer_init
Enumerated type for specifying the timer value initialization.
Enumerator
INVAL_val
Invalid initialization mode.
LSB_only
Initialization only of the LSB.
MSB_only
Initialization only of the MSB.
MSB_after_LSB
Initialization of LSB and MSB, in this order.
Definition at line 18 of file timer.h.
timer_status_field
enum timer_status_field
Enumerated type for identifying the timer status fields.
Enumerator
tsf_all
configuration/status
tsf_initial
timer initialization mode
tsf_mode
timer counting mode
tsf_base
timer counting base
Definition at line 28 of file timer.h.
Function Documentation
timer_display_conf()
int() timer_display_conf (__uint8_t timer, __uint8_t st, enum timer_status_field field)
Shows timer configuration.
Displays, in a human friendly way, the specified field of a timer status, which was read via the read-back command
Parameters
timer timer whose configuration should be displayed (Ranges from 0 to 2)
st status read via the read-back command
field status field to display in human friendly way
Returns
Return 0 upon success and non-zero otherwise
<Initialize Counter LSB only
<Initialize Counter MSB only
<Initialize LSB first and MSB afterwards
Definition at line 98 of file timer.c.
References timer_status_field_val::bcd, BCD_BIT, timer_status_field_val::byte, timer_status_field_val::count_mode, timer_status_field_val::in_mode, MODE_BITS, TIMER_INIT_BIT, TIMER_LSB_MSB, TIMER_MODE_BIT, timer_print_config(), tsf_base, tsf_initial, and tsf_mode.
timer_get_conf()
int() timer_get_conf (__uint8_t timer, __uint8_t * st)
Reads the input timer configuration (status) via read-back command.
Parameters
timer Timer whose configuration to read (Ranges from 0 to 2)
st Address of memory position to be filled with the timer config
Returns
Return 0 upon success and non-zero otherwise
<Read Back Command
<Timer 0 count register
<Control register
Definition at line 80 of file timer.c.
References TIMER_ADDR_SEL, TIMER_CTRL, TIMER_RB_CMD, TIMER_RB_COUNT_, TIMER_RB_SEL, and util_sys_inb().
timer_int_handler()
void() timer_int_handler ()
Timer 0 interrupt handler.
Increments counter
Definition at line 76 of file timer.c.
References time_counter.
timer_print_config()
int() timer_print_config (__uint8_t timer, enum timer_status_field field, union timer_status_field_val val)
Prints a timer config field value.
Returns
Returns 0 upon success and non-zero otherwise
timer_print_elapsed_time()
__uint32_t() timer_print_elapsed_time ()
Increments elapsed time count.
Returns
Returns the current time count
timer_set_frequency()
int() timer_set_frequency (__uint8_t timer, __uint32_t freq)
Changes the operating frequency of a timer.
Must use the read-back command so that it does not change the 4 LSBs (mode and BCD/binary) of the timer's control word.
Parameters
timer Timer to configure. (Ranges from 0 to 2)
freq Timer operating frequency
Returns
Return 0 upon success and non-zero otherwise
<Timer 0 count register
<clock frequency for timer in PC and AT
<Initialize Counter LSB only
<Initialize Counter MSB only
<Initialize LSB first and MSB afterwards
<Timer control word selection
<Control register
Definition at line 12 of file timer.c.
References STATUS_CONFIG, TIMER_ADDR_SEL, TIMER_CMD_SEL, TIMER_CTRL, TIMER_FREQ, timer_get_conf(), and TIMER_LSB_MSB.
timer_subscribe_int()
int() timer_subscribe_int (__uint8_t * bit_no)
Subscribes and enables Timer 0 interrupts.
Parameters
bit_no address of memory to be initialized with the bit number to be set in the mask returned upon an interrupt
Returns
Return 0 upon success and non-zero otherwise
<Timer 0 IRQ line
Definition at line 57 of file timer.c.
References subscribe_result, TIMER0_IRQ, and TIMER_SUBSCRIPTION_BITNO.
timer_unsubscribe_int()
int() timer_unsubscribe_int ()
Unsubscribes Timer 0 interrupts.
Returns
Return 0 upon success and non-zero otherwise
Definition at line 67 of file timer.c.
References subscribe_result.