OPERATION M.I.N.I.X.: Auxiliary functions
Auxiliary functions
Functions that auxiliate other methods.
Data Structures
struct ray_hit
structure with information about a shot ray.
Macros
#define BIT(n) (1 << (n))
Typedefs
typedef struct ray_hit ray_hit_t
structure with information about a shot ray.
Functions
int() util_sys_inb (int port, __uint8_t *value)
Invokes sys_inb() system call but reads the value into a uint8_t variable.
void() int_to_24 (int, int24_t *)
Converts an integer to int24_t.
__uint32_t() i24_to_int (int24_t *orig)
Converts int24_t to uint32_t.
size_t digitize (int num, size_t max_size, int *res)
Returns the digits of the number in an array.
double prod_int (vector_t *v1, vector_t *v2)
Calculates the internal product of two vectors.
double degree (vector_t *v1, vector_t *v2)
Calculates the angle of two vectors between -180 and 180.
double vec_mag (vector_t *v1)
Calculates the vector magnitude.
double vec_mag_squared (vector_t *v1)
void normalize (vector_t *v1)
double dist_positions (vector_t *v1, vector_t *v2)
Calculates the distance between two positions.
double dist_positions_squared (vector_t *v1, vector_t *v2)
Calculates the squared distance between two positions.
_Bool check_circle_rect_collision (circle_t *circle, rectangle_t *rect)
Checks if a circle and a rectangle collide. SOURCE: https://www.lazyfoo.net/tutorials/SDL/29_circular_collision_detection/index.php.
void circle_rect_distance (circle_t *circle, rectangle_t *rect, vector_t *distances)
Finds the closest distances of a circle to a rectangle.
double determinant (vector_t *v1, vector_t *v2)
Calculates the determinant of a 2x2 matrix.
double abs_double (double val)
Returns the absolute value of a double.
void (rotate_vec(vector_t *vec, double ang))
Rotates a vector counter clockwise by ang degrees Formula discovered in https://en.wikipedia.org/wiki/Rotation_matrix.
void() shoot_ray (vector_t *pos, vector_t *ray_dir, ray_hit_t *ray_hit, double range)
Shoots a ray from a given position in a given direction.
vector_t new_vec (double x, double y)
Generates a new vector.
Detailed Description
Functions that auxiliate other methods.
Macro Definition Documentation
BIT
#define BIT (n) (1 << (n))
Definition at line 15 of file utils.h.
Typedef Documentation
ray_hit_t
typedef struct ray_hit ray_hit_t
structure with information about a shot ray.
Function Documentation
abs_double()
double abs_double (double val)
Returns the absolute value of a double.
Parameters
val The value to return the absolute functions
Returns
Absolute value of a double as a double
Definition at line 134 of file utils.c.
check_circle_rect_collision()
_Bool check_circle_rect_collision (circle_t * circle, rectangle_t * rect)
Checks if a circle and a rectangle collide. SOURCE: https://www.lazyfoo.net/tutorials/SDL/29_circular_collision_detection/index.php.
Parameters
circle Pointer to a circle_t.
rect Pointer to a rectangle_t.
Returns
True if collision occurs, false if not.
Definition at line 93 of file utils.c.
References circle::center, dist_positions_squared(), rectangle::height, rectangle::left_corner, circle::radius, rectangle::width, vector::x, and vector::y.
circle_rect_distance()
void circle_rect_distance (circle_t * circle, rectangle_t * rect, vector_t * distances)
Finds the closest distances of a circle to a rectangle.
Parameters
circle Circle
rect Rectangle
[out] distances Resulting vector
Definition at line 113 of file utils.c.
References circle::center, rectangle::height, rectangle::left_corner, rectangle::width, vector::x, and vector::y.
degree()
double degree (vector_t * v1, vector_t * v2)
Calculates the angle of two vectors between -180 and 180.
Parameters
v1 Pointer to first vector
v2 Pointer to second vector
Definition at line 57 of file utils.c.
References determinant(), and prod_int().
determinant()
double determinant (vector_t * v1, vector_t * v2)
Calculates the determinant of a 2x2 matrix.
Parameters
v1 Pointer to first the vector representing the first column
v2 Pointer to first the vector representing the first column
Definition at line 130 of file utils.c.
References vector::x, and vector::y.
digitize()
size_t digitize (int num, size_t max_size, int * res)
Returns the digits of the number in an array.
Parameters
num The value to digitize
max_size Max digits - Truncates the first digits
res Array to fill
Definition at line 40 of file utils.c.
dist_positions()
double dist_positions (vector_t * v1, vector_t * v2)
Calculates the distance between two positions.
Parameters
v1 Pointer to first vector position
v2 Pointer to second vector position
Returns
the distance between positions.
Definition at line 85 of file utils.c.
References vector::x, and vector::y.
dist_positions_squared()
double dist_positions_squared (vector_t * v1, vector_t * v2)
Calculates the squared distance between two positions.
Parameters
v1 Pointer to first vector position
v2 Pointer to second vector position
Returns
the squared distance between positions.
Definition at line 89 of file utils.c.
References vector::x, and vector::y.
i24_to_int()
__uint32_t() i24_to_int (int24_t * orig)
Converts int24_t to uint32_t.
Parameters
orig Input value
Returns
Converted value
Definition at line 30 of file utils.c.
int_to_24()
void() int_to_24 (int , int24_t *)
Converts an integer to int24_t.
Parameters
int Input value
[out] return value
Definition at line 24 of file utils.c.
new_vec()
vector_t new_vec (double x, double y)
Generates a new vector.
Parameters
x X value
y Y value
Returns
Converted vector_t
Definition at line 149 of file utils.c.
References vector::x, and vector::y.
normalize()
void normalize (vector_t * v1)
Normalizes a vector
Parameters
v1 pointer to the input (and return) vector
Definition at line 78 of file utils.c.
References vec_mag(), vector::x, and vector::y.
prod_int()
double prod_int (vector_t * v1, vector_t * v2)
Calculates the internal product of two vectors.
Parameters
v1 Pointer to first vector
v2 Pointer to second vector
Definition at line 53 of file utils.c.
References vector::x, and vector::y.
shoot_ray()
void() shoot_ray (vector_t * pos, vector_t * ray_dir, ray_hit_t * ray_hit, double range)
Shoots a ray from a given position in a given direction.
Uses the DDA algorithm (described in more detail here: https://lodev.org/cgtutor/raycasting.html) to traverse the map and check collision with walls. Can be used with a range.
Parameters
pos pointer to the starting position of the ray
ray_dir pointer to the direction of the ray
ray_hit pointer to a ray_hit_t structure. The return of this function is stored here.
range the maximum range of the wall (in blocks), 0 if unlimited
Definition at line 156 of file utils.c.
References map::columns, ray_hit::distance, ray_hit::hit, map::lines, ray_hit::map_pos, map::matrix, ray_hit::side, vector::x, coordinate::x, vector::y, and coordinate::y.
util_sys_inb()
int() util_sys_inb (int port, __uint8_t * value)
Invokes sys_inb() system call but reads the value into a uint8_t variable.
Parameters
port the input port that is to be read
value a pointer to the variable that is to be update with the value read
Returns
Return 0 upon success and non-zero otherwise
Definition at line 12 of file utils.c.
vec_mag()
double vec_mag (vector_t * v1)
Calculates the vector magnitude.
Parameters
v1 Pointer to first vector
Definition at line 70 of file utils.c.
References vector::x, and vector::y.
vec_mag_squared()
double vec_mag_squared (vector_t * v1)
Definition at line 74 of file utils.c.
References vector::x, and vector::y.
void()
void (rotate_vec(vector_t *vec, double ang))
Rotates a vector counter clockwise by ang degrees Formula discovered in https://en.wikipedia.org/wiki/Rotation_matrix.
Parameters
vec Vector to rotate
ang Angle in degrees to rotate
Definition at line 139 of file utils.c.
References vector::x, and vector::y.