OPERATION M.I.N.I.X.: Networking
Networking
Functions used to control the communication protocol.
Data Structures
struct network_packet
Macros
#define DATA_SHOOTDOWN BIT(0)
#define DATA_CTRLDOWN BIT(1)
#define DATA_SHIFTDOWN BIT(2)
#define DATA_DDOWN BIT(3)
#define DATA_SDOWN BIT(4)
#define DATA_ADOWN BIT(5)
#define DATA_WDOWN BIT(6)
#define DATA_MOUSE_MSB BIT(7)
#define DATA_GUN_DOWN(n) BIT(n-1)
#define DATA_GUN_DOWN_1 BIT(0)
#define DATA_GUN_DOWN_2 BIT(1)
#define DATA_GUN_DOWN_3 BIT(2)
#define DATA_GUN_BITS (BIT(0) | BIT(1) | BIT(2))
#define DATA_CONFIRM_PACKET (BIT(7) | BIT(5) | BIT(3))
#define DATA_CONFIRM_MASK 0xf8
#define DATA_BYTES 3
#define UART_JOIN_REQUEST 'J'
#define UART_SYNC_PASSWORD "START"
#define UART_SYNC_RESPONSE "BEGIN"
#define UART_PASSWORD_SIZE 5
#define UART_ACK 'O'
#define UART_GET_RESPONSE 'P'
#define UART_WIN_GAME "WIN"
#define UART_LOSE_GAME "LOS"
#define LOSE_GAME_ERR 5
#define WIN_GAME_ERR 6
#define UART_SYNC_TRIES 30*60
#define UART_PACKET_TRIES 8*60
Typedefs
typedef struct network_packet network_packet_t
typedef enum network_state network_state_t
Network state.
Enumerations
enum network_state {
INIT, WAITING, LINKED, CONNECTED,
DISCONNECTED, CLEANUP
}
Network state.
Functions
network_state_t() get_network_state ()
Gets the current network state.
__uint8_t get_network_player ()
Gets player id in the network.
void() set_network_state (network_state_t nstate)
Sets a network state.
void() uart_sync ()
Uart sync handler According to the state of the network, performs different operations to complete the sync between the 2 pc's.
int() uart_send_data (player_info_t *ply)
Sends a data packet through the UART.
int() decode_data (__uint8_t *data, network_packet_t *pkt)
Turns a received byte array from communication into a readable format.
int() encode_data (__uint8_t *data, network_packet_t *pkt)
Encodes information into a byte array to be sent by the UART.
void() print_net_packet (network_packet_t pkt)
Prints a network packet Only useful for debugging.
int() encode_packet (network_packet_t *pkt, player_info_t *ply)
Encodes movement and fills a network_packet_t.
int() decode_packet (network_packet_t *pkt, player_info_t *ply)
Decodes a network_packet_t and fills a controls_t object.
int() uart_receive_data (player_info_t *ply)
Receives data from the enemy player.
int() uart_send_string (char *word, size_t size)
Sends a string to the uart Useful when a game ends to confirm and reduce sync errors.
Detailed Description
Functions used to control the communication protocol.
Macro Definition Documentation
DATA_ADOWN
#define DATA_ADOWN BIT(5)
Definition at line 48 of file networking.h.
DATA_BYTES
#define DATA_BYTES 3
Definition at line 60 of file networking.h.
DATA_CONFIRM_MASK
#define DATA_CONFIRM_MASK 0xf8
Definition at line 58 of file networking.h.
DATA_CONFIRM_PACKET
#define DATA_CONFIRM_PACKET (BIT(7) | BIT(5) | BIT(3))
Definition at line 57 of file networking.h.
DATA_CTRLDOWN
#define DATA_CTRLDOWN BIT(1)
Definition at line 44 of file networking.h.
DATA_DDOWN
#define DATA_DDOWN BIT(3)
Definition at line 46 of file networking.h.
DATA_GUN_BITS
#define DATA_GUN_BITS (BIT(0) | BIT(1) | BIT(2))
Definition at line 55 of file networking.h.
DATA_GUN_DOWN
#define DATA_GUN_DOWN (n) BIT(n-1)
Definition at line 51 of file networking.h.
DATA_GUN_DOWN_1
#define DATA_GUN_DOWN_1 BIT(0)
Definition at line 52 of file networking.h.
DATA_GUN_DOWN_2
#define DATA_GUN_DOWN_2 BIT(1)
Definition at line 53 of file networking.h.
DATA_GUN_DOWN_3
#define DATA_GUN_DOWN_3 BIT(2)
Definition at line 54 of file networking.h.
DATA_MOUSE_MSB
#define DATA_MOUSE_MSB BIT(7)
Definition at line 50 of file networking.h.
DATA_SDOWN
#define DATA_SDOWN BIT(4)
Definition at line 47 of file networking.h.
DATA_SHIFTDOWN
#define DATA_SHIFTDOWN BIT(2)
Definition at line 45 of file networking.h.
DATA_SHOOTDOWN
#define DATA_SHOOTDOWN BIT(0)
Packet parsing
Definition at line 43 of file networking.h.
DATA_WDOWN
#define DATA_WDOWN BIT(6)
Definition at line 49 of file networking.h.
LOSE_GAME_ERR
#define LOSE_GAME_ERR 5
Definition at line 75 of file networking.h.
UART_ACK
#define UART_ACK 'O'
Definition at line 69 of file networking.h.
UART_GET_RESPONSE
#define UART_GET_RESPONSE 'P'
Definition at line 70 of file networking.h.
UART_JOIN_REQUEST
#define UART_JOIN_REQUEST 'J'
Uart sync
Definition at line 65 of file networking.h.
UART_LOSE_GAME
#define UART_LOSE_GAME "LOS"
Definition at line 73 of file networking.h.
UART_PACKET_TRIES
#define UART_PACKET_TRIES 8*60
Definition at line 79 of file networking.h.
UART_PASSWORD_SIZE
#define UART_PASSWORD_SIZE 5
Definition at line 68 of file networking.h.
UART_SYNC_PASSWORD
#define UART_SYNC_PASSWORD "START"
Definition at line 66 of file networking.h.
UART_SYNC_RESPONSE
#define UART_SYNC_RESPONSE "BEGIN"
Definition at line 67 of file networking.h.
UART_SYNC_TRIES
#define UART_SYNC_TRIES 30*60
Definition at line 78 of file networking.h.
UART_WIN_GAME
#define UART_WIN_GAME "WIN"
Definition at line 72 of file networking.h.
WIN_GAME_ERR
#define WIN_GAME_ERR 6
Definition at line 76 of file networking.h.
Typedef Documentation
network_packet_t
typedef struct network_packet network_packet_t
network_state_t
typedef enum network_state network_state_t
Network state.
Enumeration Type Documentation
network_state
enum network_state
Network state.
Enumerator
INIT
Initial state.
WAITING
Waiting for a connection.
LINKED
Both pc's are linked.
CONNECTED
Both pc's are connected, in game.
DISCONNECTED
Disconnected.
CLEANUP
Cleaning up garbage data from uart.
Definition at line 84 of file networking.h.
Function Documentation
decode_data()
int() decode_data (__uint8_t * data, network_packet_t * pkt)
Turns a received byte array from communication into a readable format.
Parameters
data The byte array received from the UART.
[out] pkt The readable format.
Returns
OK if no errors occurred.
Definition at line 248 of file networking.c.
References network_packet::a_down, network_packet::ctrl_down, network_packet::d_down, DATA_ADOWN, DATA_CTRLDOWN, DATA_DDOWN, DATA_GUN_BITS, DATA_GUN_DOWN_1, DATA_GUN_DOWN_2, DATA_GUN_DOWN_3, DATA_MOUSE_MSB, DATA_SDOWN, DATA_SHIFTDOWN, DATA_SHOOTDOWN, DATA_WDOWN, network_packet::gun_down, network_packet::mouse_byte, network_packet::mouse_msb, network_packet::s_down, network_packet::shift_down, network_packet::shoot_down, and network_packet::w_down.
decode_packet()
int() decode_packet (network_packet_t * pkt, player_info_t * ply)
Decodes a network_packet_t and fills a controls_t object.
Definition at line 200 of file networking.c.
References network_packet::a_down, network_packet::ctrl_down, network_packet::d_down, network_packet::gun_down, network_packet::mouse_byte, network_packet::mouse_msb, network_packet::s_down, network_packet::shift_down, network_packet::shoot_down, and network_packet::w_down.
encode_data()
int() encode_data (__uint8_t * data, network_packet_t * pkt)
Encodes information into a byte array to be sent by the UART.
Parameters
[out] data The byte array.
pkt The readable format.
Returns
OK if no errors occurred.
Definition at line 219 of file networking.c.
References network_packet::a_down, network_packet::ctrl_down, network_packet::d_down, DATA_ADOWN, DATA_CONFIRM_PACKET, DATA_CTRLDOWN, DATA_DDOWN, DATA_GUN_DOWN, DATA_MOUSE_MSB, DATA_SDOWN, DATA_SHIFTDOWN, DATA_SHOOTDOWN, DATA_WDOWN, network_packet::gun_down, network_packet::mouse_byte, network_packet::mouse_msb, network_packet::s_down, network_packet::shift_down, network_packet::shoot_down, and network_packet::w_down.
encode_packet()
int() encode_packet (network_packet_t * pkt, player_info_t * ply)
Encodes movement and fills a network_packet_t.
Definition at line 169 of file networking.c.
References network_packet::a_down, network_packet::ctrl_down, network_packet::d_down, network_packet::gun_down, network_packet::mouse_byte, network_packet::mouse_msb, network_packet::s_down, network_packet::shift_down, network_packet::shoot_down, and network_packet::w_down.
get_network_player()
__uint8_t get_network_player ()
Gets player id in the network.
Returns
Player id
Definition at line 14 of file networking.c.
References player.
get_network_state()
network_state_t() get_network_state ()
Gets the current network state.
Returns
Network state
Definition at line 18 of file networking.c.
References state.
print_net_packet()
void() print_net_packet (network_packet_t pkt)
Prints a network packet Only useful for debugging.
Parameters
pkt Packet to print
Definition at line 241 of file networking.c.
References network_packet::a_down, network_packet::ctrl_down, network_packet::d_down, network_packet::gun_down, network_packet::mouse_byte, network_packet::mouse_msb, network_packet::s_down, network_packet::shift_down, network_packet::shoot_down, and network_packet::w_down.
set_network_state()
void() set_network_state (network_state_t nstate)
Sets a network state.
Parameters
New network state
Definition at line 22 of file networking.c.
References state.
uart_receive_data()
int() uart_receive_data (player_info_t * ply)
Receives data from the enemy player.
Parameters
ply Enemy
Definition at line 300 of file networking.c.
References DATA_BYTES, DATA_CONFIRM_MASK, DATA_CONFIRM_PACKET, decode_data(), decode_packet(), DISCONNECTED, LOSE_GAME_ERR, packet_idx, packet_tries, player_int_ih(), set_network_state(), uart_bytes_cmp(), UART_LOSE_GAME, UART_PACKET_TRIES, uart_recv_front(), UART_WIN_GAME, and WIN_GAME_ERR.
uart_send_data()
int() uart_send_data (player_info_t * ply)
Sends a data packet through the UART.
Sends data to the enemy player.
Parameters
ply The player structure pointer
Returns
OK if no errors occurred.
ply Player's origin of data
Definition at line 277 of file networking.c.
References DATA_BYTES, encode_data(), encode_packet(), uart_push_transmit(), and uart_safe_transmit().
uart_send_string()
int() uart_send_string (char * word, size_t size)
Sends a string to the uart Useful when a game ends to confirm and reduce sync errors.
Parameters
word The string
size Size of the string
Definition at line 269 of file networking.c.
References uart_push_transmit(), and uart_safe_transmit().
uart_sync()
void() uart_sync ()
Uart sync handler According to the state of the network, performs different operations to complete the sync between the 2 pc's.
Definition at line 113 of file networking.c.
References CLEANUP, empty_recv_queue(), empty_transmit_queue(), idx, INIT, LINKED, packet_idx, packet_tries, reset_sync(), send_join_request(), state, uart_init_fifo(), UART_MAX_TRIES, uart_receive_byte(), uart_sync_connect(), uart_sync_link(), UART_SYNC_TRIES, and WAITING.