OPERATION M.I.N.I.X.: GUN
GUN
Functions and data_types related to the guns.
Data Structures
struct gun
Data structure that describes a gun type.
struct gun_instance
Structure that describes an active gun.
Typedefs
typedef enum gun_state gun_state_t
State of the weapon.
typedef struct gun gun_t
Data structure that describes a gun type.
typedef struct gun_instance gun_instance_t
Structure that describes an active gun.
Enumerations
enum gun_state {
INVENTORY, INITIAL, CHARGING, READY,
COOLDOWN, NO_AMMO, RELOADING
}
State of the weapon.
Functions
void update_gun_state (gun_instance_t *gun, _Bool shot, _Bool player)
Function called to update a gun's state Call this function upon after trying to shoot a bullet.
void add_packets (gun_instance_t *gun, unsigned int num_packets)
Adds packets to the gun.
void() reload_gun (gun_instance_t *gun)
Function to reload the gun.
int() init_guns ()
Sets guns to default settings and adds them to gun array.
gun_t() get_gun (int gun_index)
Gets a gun from the gun array.
gun_instance_t() create_gun_instance (int gun_index, int start_ammo, int start_packets)
Creates a gun instance to be used in a player.
int() free_gun_anims (gun_t *g)
int() init_gun_anims (gun_t *g, double anim_speed_multiplier)
Initialize gun animation.
int() init_rifle_anims (gun_t *g, double anim_speed_multiplier)
Initialize rifle animation.
int() init_ray_anims (gun_t *g, double anim_speed_multiplier)
Initialize ray animation.
Detailed Description
Functions and data_types related to the guns.
Typedef Documentation
gun_instance_t
typedef struct gun_instance gun_instance_t
Structure that describes an active gun.
gun_state_t
typedef enum gun_state gun_state_t
State of the weapon.
gun_t
typedef struct gun gun_t
Data structure that describes a gun type.
Enumeration Type Documentation
gun_state
enum gun_state
State of the weapon.
Enumerator
INVENTORY
Currently only stored in inventory.
INITIAL
Taken out of the inventory.
CHARGING
Time after taking weapon from inventory.
READY
Ready to be shot.
COOLDOWN
Waiting time between shots.
NO_AMMO
No ammo in gun.
RELOADING
Reloading.
Definition at line 19 of file gun.h.
Function Documentation
add_packets()
void add_packets (gun_instance_t * gun, unsigned int num_packets)
Adds packets to the gun.
Parameters
gun Gun instance pointer
num_packets Number of packets to be added
Definition at line 74 of file gun.c.
create_gun_instance()
gun_instance_t() create_gun_instance (int gun_index, int start_ammo, int start_packets)
Creates a gun instance to be used in a player.
Parameters
gun_index index of the gun.
start_ammo starting ammunition
start_packets starting number of ammo packets
Returns
a copy of the gun type.
Definition at line 201 of file gun.c.
References ammo_per_packet, gun_instance::curr_ammo, gun_instance::curr_anim, gun_instance::curr_packets, get_gun(), gun_instance::gun, gun_instance::gun_index, INVENTORY, gun_instance::last_op_tick, max_packets, and gun_instance::state.
free_gun_anims()
int() free_gun_anims (gun_t * g)
Definition at line 85 of file gun.c.
get_gun()
gun_t() get_gun (int gun_index)
Gets a gun from the gun array.
Parameters
gun_index index of the gun array.
Returns
a copy of the gun type.
Definition at line 192 of file gun.c.
References guns.
init_gun_anims()
int() init_gun_anims (gun_t * g, double anim_speed_multiplier)
Initialize gun animation.
Parameters
g Pointer to the corresponding gun
anim_speed_multiplier Value to multiply the maximum number of ticks calculated per sprite. Should be between ]0, 1]
Idle animation
Fire animation
Definition at line 215 of file gun.c.
References animations, cooldown_time, animated_sprite::cur_frame, animated_sprite::frames, animated_sprite::frames_per_sprite, num_anims, animated_sprite::num_fig, and animated_sprite::sprite.
init_guns()
int() init_guns ()
Sets guns to default settings and adds them to gun array.
Returns
0 on success.
Definition at line 91 of file gun.c.
References ammo_index, ammo_per_fire, ammo_per_packet, automatic, burst, charge_time, cooldown_time, damage, guns, init_gun_anims(), init_ray_anims(), init_rifle_anims(), max_packets, menu_sprite, name, range, reload_time, and spread.
init_ray_anims()
int() init_ray_anims (gun_t * g, double anim_speed_multiplier)
Initialize ray animation.
Parameters
g Pointer to the corresponding gun
anim_speed_multiplier Value to multiply the maximum number of ticks calculated per sprite. Should be between ]0, 1]
Idle animation
Fire animation
Definition at line 310 of file gun.c.
References animations, cooldown_time, animated_sprite::cur_frame, animated_sprite::frames, animated_sprite::frames_per_sprite, num_anims, animated_sprite::num_fig, and animated_sprite::sprite.
init_rifle_anims()
int() init_rifle_anims (gun_t * g, double anim_speed_multiplier)
Initialize rifle animation.
Parameters
g Pointer to the corresponding gun
anim_speed_multiplier Value to multiply the maximum number of ticks calculated per sprite. Should be between ]0, 1]
Idle animation
Fire animation
Definition at line 264 of file gun.c.
References animations, cooldown_time, animated_sprite::cur_frame, animated_sprite::frames, animated_sprite::frames_per_sprite, num_anims, animated_sprite::num_fig, and animated_sprite::sprite.
reload_gun()
void() reload_gun (gun_instance_t * gun)
Function to reload the gun.
Parameters
Gun pointer
Definition at line 78 of file gun.c.
update_gun_state()
void update_gun_state (gun_instance_t * gun, _Bool shot, _Bool player)
Function called to update a gun's state Call this function upon after trying to shoot a bullet.
Parameters
gun Gun instance pointer
shot If the gun was shot or not
Definition at line 12 of file gun.c.
References animations, charge_time, CHARGING, COOLDOWN, cooldown_time, gun_instance::curr_ammo, gun_instance::curr_anim, gun_instance::curr_packets, gun_instance::gun, INITIAL, gun_instance::last_op_tick, NO_AMMO, player, READY, reload_gun(), reload_time, RELOADING, gun_instance::state, time_counter, and update_anim().