OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/game/level_manager.c File Reference
level_manager.c File Reference
#include "level_manager.h"
#include "controls/controls.h"
#include "file/map.h"
#include "graphics/render.h"
#include "graphics/graphics.h"
#include "lib/i8042.h"
#include "lib/kbc.h"
#include "lib/timer.h"
#include "lib/video_graphics.h"
#include "lib/sprites.h"
#include "utils/data_types.h"
#include "player/player.h"
#include "guns/gun.h"
#include "pickups/pickups.h"
#include "ai/enemy_controller.h"
#include "../data/sprites/inv_sprites.h"
#include "../game/game_manager.h"
#include "../lib/rs232.h"
#include "../lib/uart.h"
#include "../lib/rtc_controller.h"
#include <stdint.h>
Functions
__int8_t get_curr_lvl ()
Returns level number to identify in the menu if there is a next level or not The value -1 represents multiplayer.
void setup_game_1 ()
void setup_game_2 ()
Setup level 2.
int init_game (__uint8_t *t_bit_no, __uint8_t *ms_bit_no, __uint8_t *kb_bit_no, __uint8_t *uart_bit_no, __uint8_t *rtc_bit_no)
Load modules of the game from the lib and initializes everything.
int load_level (int num_map, int mode, int player)
Loads a specified level.
int() setup_multiplayer (int player)
Setups multiplayer game mode and level.
int free_level ()
Free memory allocated by load level and setup_game_x.
int free_game ()
Free the memory allocated by load_game.
Variables
player_info_t player
player_info_t * enemies
map_t map
static __int8_t curr_lvl
Function Documentation
setup_game_1()
void setup_game_1 ()
Definition at line 37 of file level_manager.c.
References add_ammo(), add_armor(), add_medkit(), BOT, create_gun_instance(), enemies, GAME, init_enemy(), init_player(), PLAYER, set_state(), vector::x, and vector::y.
Variable Documentation
curr_lvl
__int8_t curr_lvl static
Definition at line 31 of file level_manager.c.
enemies
player_info_t* enemies extern
Definition at line 15 of file player.c.
map
map_t map
Definition at line 29 of file level_manager.c.
player
player_info_t player extern
Definition at line 13 of file player.c.