OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/networking/networking.c File Reference
networking.c File Reference
#include "networking.h"
#include "../lib/uart.h"
#include "../lib/rs232.h"
#include "../controls/controls.h"
#include <math.h>
Functions
__uint8_t get_network_player ()
Gets player id in the network.
network_state_t() get_network_state ()
Gets the current network state.
void() set_network_state (network_state_t nstate)
Sets a network state.
void() send_join_request ()
int() uart_sync_link ()
int() uart_sync_connect ()
void() reset_sync ()
void() uart_sync ()
Uart sync handler According to the state of the network, performs different operations to complete the sync between the 2 pc's.
int() encode_packet (network_packet_t *pkt, player_info_t *ply)
Encodes movement and fills a network_packet_t.
int() decode_packet (network_packet_t *pkt, player_info_t *ply)
Decodes a network_packet_t and fills a controls_t object.
int() encode_data (__uint8_t *data, network_packet_t *pkt)
Encodes information into a byte array to be sent by the UART.
void() print_net_packet (network_packet_t pkt)
Prints a network packet Only useful for debugging.
int() decode_data (__uint8_t *data, network_packet_t *pkt)
Turns a received byte array from communication into a readable format.
int() uart_send_string (char *word, size_t size)
Sends a string to the uart Useful when a game ends to confirm and reduce sync errors.
int() uart_send_data (player_info_t *ply)
Sends a data packet through the UART.
_Bool uart_bytes_cmp (void *b1, void *b2, size_t size)
int() uart_receive_data (player_info_t *ply)
Receives data from the enemy player.
Variables
static __uint8_t idx = 0
static __uint8_t packet_idx = 0
static __uint32_t packet_tries = 0
static network_state_t state = CLEANUP
static __uint8_t player
Function Documentation
reset_sync()
void() reset_sync ()
Definition at line 108 of file networking.c.
References CLEANUP, idx, and state.
send_join_request()
void() send_join_request ()
Definition at line 26 of file networking.c.
References UART_JOIN_REQUEST, and uart_safe_transmit().
uart_bytes_cmp()
_Bool uart_bytes_cmp (void * b1, void * b2, size_t size)
Definition at line 292 of file networking.c.
uart_sync_connect()
int() uart_sync_connect ()
Definition at line 69 of file networking.c.
References CONNECTED, empty_transmit_queue(), idx, player, state, UART_ACK, UART_ERROR_CODE, UART_GET_RESPONSE, UART_PASSWORD_SIZE, uart_recv_front(), uart_safe_transmit(), and UART_SYNC_RESPONSE.
uart_sync_link()
int() uart_sync_link ()
Definition at line 30 of file networking.c.
References empty_transmit_queue(), idx, LINKED, state, UART_ACK, UART_ERROR_CODE, UART_GET_RESPONSE, UART_JOIN_REQUEST, UART_PASSWORD_SIZE, uart_recv_front(), uart_safe_transmit(), and UART_SYNC_PASSWORD.
Variable Documentation
idx
__uint8_t idx = 0 static
Definition at line 8 of file networking.c.
packet_idx
__uint8_t packet_idx = 0 static
Definition at line 9 of file networking.c.
packet_tries
__uint32_t packet_tries = 0 static
Definition at line 10 of file networking.c.
player
__uint8_t player static
Definition at line 12 of file networking.c.
state
network_state_t state = CLEANUP static
Definition at line 11 of file networking.c.