OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/pickups/pickups.c File Reference
pickups.c File Reference
#include "pickups.h"
#include "../lib/errors.h"
#include "../lib/sprites.h"
#include "../../data/sprites/pickups/pickup_sprites.h"
Functions
int() init_ammo_anims (pickup_t *pickup, int ammo_index)
int() init_medi_anims (pickup_t *pickup)
int() init_armor_anims (pickup_t *pickup)
static _Bool() pickup_ammo (player_info_t *player, void *pickup_det)
Pickup handler for ammo pickups. Overrides virtual function.
size_t add_ammo (vector_t *position, double radius, __uint16_t ammo_index, __uint16_t packets)
Adds ammo to the pickups.
static _Bool() pickup_medkit (player_info_t *player, void *pickup_det)
Pickup handler for medkit pickups. Overrides virtual function.
size_t add_medkit (vector_t *position, double radius, __uint16_t health)
Adds medkit to the pickups.
static _Bool() pickup_armor (player_info_t *player, void *pickup_det)
Pickup handler for armor pickups. Overrides virtual function.
size_t add_armor (vector_t *position, double radius, __uint16_t armor_quantity)
Adds armor to the pickups.
int() init_collision_table (size_t width, size_t height)
Initializes the pickup collision table.
void() update_pickups ()
Updates pickup animations.
void() free_collision_table ()
Frees resources used up by the collision table.
int() add_collision (pickup_t *pickup, size_t pickup_index)
void() remove_collision (vector_t *position, size_t pickup_index)
size_t() check_player_pickup_collision (player_info_t *player)
Checks if a player can pick up an item.
void() print_table ()
size_t() add_pickup (pickup_t *pickup)
Adds pickup to pickup array and sets its position in the collision table.
_Bool() pickup_index (player_info_t *player, unsigned index)
Picks up an item with a given index.
pickup_t() get_pickup (unsigned index)
Gets a copy of a pickup from the pickup array given its index.
size_t() get_pickups_size ()
Gets the number of pickups + 1.
void() delete_pickup (unsigned index)
Removes a pickup from the collision table and ignores it in the pickup array.
void() free_pickups ()
Frees resources used up by the pickup array.
Variables
pickup_t * pickups = ((void *)0)
collision_table_t collision_table
size_t pickups_size = 0
pickup_vtable_t AMMO [] = {{ &pickup_ammo }}
sets the virtual table for ammunition pickups.
pickup_vtable_t MEDKIT [] = {{ &pickup_medkit }}
sets the virtual table for medkit pickups.
pickup_vtable_t ARMOR [] = {{ &pickup_armor }}
sets the virtual table for armor pickups.
Function Documentation
add_collision()
int() add_collision (pickup_t * pickup, size_t pickup_index)
Definition at line 210 of file pickups.c.
References BAD_ALLOC, circle::center, check_circle_rect_collision(), pickup::collider, COLLISION_LIST_ALLOC_STEP, collision_table::height, rectangle::height, collision_list::indexes, rectangle::left_corner, collision_list::max_indexes, collision_list::num_of_indexes, pickup_index(), collision_table::table, collision_table::width, rectangle::width, vector::x, pair::x, vector::y, and pair::y.
init_ammo_anims()
int() init_ammo_anims (pickup_t * pickup, int ammo_index)
Definition at line 10 of file pickups.c.
References pickup::animation, BAD_ALLOC, animated_sprite::cur_frame, animated_sprite::frames, animated_sprite::frames_per_sprite, animated_sprite::num_fig, and animated_sprite::sprite.
init_armor_anims()
int() init_armor_anims (pickup_t * pickup)
Definition at line 40 of file pickups.c.
References pickup::animation, BAD_ALLOC, animated_sprite::cur_frame, animated_sprite::frames, animated_sprite::frames_per_sprite, animated_sprite::num_fig, and animated_sprite::sprite.
init_medi_anims()
int() init_medi_anims (pickup_t * pickup)
Definition at line 26 of file pickups.c.
References pickup::animation, BAD_ALLOC, animated_sprite::cur_frame, animated_sprite::frames, animated_sprite::frames_per_sprite, animated_sprite::num_fig, and animated_sprite::sprite.
pickup_ammo()
static _Bool() pickup_ammo (player_info_t * player, void * pickup_det) static
Pickup handler for ammo pickups. Overrides virtual function.
Definition at line 58 of file pickups.c.
References gun::ammo_index, ammo::ammo_index, gun_instance::curr_packets, gun_instance::gun, player_info::guns, idx, player_info::inventory_size, gun::max_packets, ammo::packets, and player.
pickup_armor()
static _Bool() pickup_armor (player_info_t * player, void * pickup_det) static
Pickup handler for armor pickups. Overrides virtual function.
Definition at line 139 of file pickups.c.
References armor::armor, player_info::armor, player_info::max_armor, and player.
pickup_medkit()
static _Bool() pickup_medkit (player_info_t * player, void * pickup_det) static
Pickup handler for medkit pickups. Overrides virtual function.
Definition at line 103 of file pickups.c.
References medkit::health, player_info::health, player_info::max_health, and player.
remove_collision()
void() remove_collision (vector_t * position, size_t pickup_index)
Definition at line 250 of file pickups.c.
References collision_table::height, collision_list::indexes, collision_list::num_of_indexes, pickup_index(), collision_table::table, collision_table::width, vector::x, pair::x, vector::y, and pair::y.
Variable Documentation
ARMOR
pickup_vtable_t ARMOR[] = {{ &pickup_armor }}
sets the virtual table for armor pickups.
Definition at line 154 of file pickups.c.
collision_table
collision_table_t collision_table
Definition at line 7 of file pickups.c.
MEDKIT
pickup_vtable_t MEDKIT[] = {{ &pickup_medkit }}
sets the virtual table for medkit pickups.
Definition at line 118 of file pickups.c.
pickups
pickup_t* pickups = ((void *)0)
Definition at line 6 of file pickups.c.
pickups_size
size_t pickups_size = 0
Definition at line 8 of file pickups.c.