OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/player/player.c File Reference
player.c File Reference
#include "player.h"
#include "../graphics/render.h"
#include "../utils/utils.h"
#include "../lib/sprites.h"
#include "../../data/sprites/player/player_sprites.h"
#include "../pickups/pickups.h"
#include <math.h>
#include "../game/game_manager.h"
#include <lcom/xpm.h>
#include <lcom/lcf.h>
#include <stdint.h>
Functions
int() reset_player_mouse_movm (player_info_t *ply)
Reset player's mouse desl to 0.
player_info_t * get_player ()
Returns player's 1 pointer.
player_info_t * get_mp_enemy_player ()
Returns player's 2 (mulitplayer) pointer.
int() init_player_anims (player_info_t *p)
Initializes player animations.
int() free_player_anims (player_info_t *p)
Frees the memory allocated by init_player_anims()
void init_player_ctrls ()
Initializes player controls to use in menus.
void init_player (player_type_t type, vector_t *position, vector_t *direction, double radius, int health, int max_health, int armor, int max_armor, gun_instance_t *instances, int num_guns)
Function to construct a player or bot.
void free_players ()
Frees the memory allocated by init_player.
void() update_player_controls (player_info_t *ply)
State machine for the mouse to detect single tap events.
_Bool() hit_player (double *dist, player_info_t *p1, player_info_t *p2)
Verifies if the second player was hit by a shot taken by p1 Calculates tangent points of p2 and verifies direction of p1 and checks if its within bounds of those thangent lines.
void() switch_gun (player_info_t *ply, int index)
Function to switch the gun.
_Bool() fire (player_info_t *ply)
vector_t() player_wall_collision (player_info_t *ply, vector_t *new_pos)
void() player_int_ih (player_info_t *ply)
Player int handler Analyses controls and moves, shoots and select animations that should be played according to them.
void() bot_int_ih ()
Handle bots events.
Variables
player_info_t player
player_info_t * enemies
size_t num_enemies = 0
map_t map
tick_t time_counter
settings_t settings
Function Documentation
fire()
_Bool() fire (player_info_t * ply)
Definition at line 293 of file player.c.
References gun::ammo_per_fire, player_info::armor, gun_instance::curr_ammo, gun_instance::curr_anim, gun::damage, player_info::direction, ray_hit::distance, enemies, gun_instance::gun, player_info::gun_index, player_info::guns, player_info::health, ray_hit::hit, hit_player(), num_enemies, player, PLAYER, player_info::position, gun::range, READY, shoot_ray(), gun_instance::state, and player_info::type.
player_wall_collision()
vector_t() player_wall_collision (player_info_t * ply, vector_t * new_pos)
Definition at line 356 of file player.c.
References circle::center, circle_rect_distance(), map::columns, rectangle::height, rectangle::left_corner, map::lines, map::matrix, player_info::radius, circle::radius, vec_mag_squared(), rectangle::width, vector::x, pair::x, vector::y, and pair::y.
update_player_controls()
void() update_player_controls (player_info_t * ply)
State machine for the mouse to detect single tap events.
Parameters
The player to detect
Definition at line 232 of file player.c.
References KEY_DOWN, and KEY_UP.
Variable Documentation
enemies
player_info_t* enemies
Definition at line 15 of file player.c.
map
map_t map extern
Definition at line 29 of file level_manager.c.
num_enemies
size_t num_enemies = 0
Definition at line 17 of file player.c.
player
player_info_t player
Definition at line 13 of file player.c.
settings
settings_t settings
Definition at line 21 of file player.c.
time_counter
tick_t time_counter extern
Definition at line 10 of file timer.c.