OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/graphics/render.c File Reference
render.c File Reference
#include "render.h"
#include "../file/map.h"
#include "../lib/timer.h"
#include "../lib/video_graphics.h"
#include "../player/player.h"
#include "../utils/data_types.h"
#include "../utils/utils.h"
#include "../graphics/graphics.h"
#include "../../data/textures/walls.h"
#include "../controls/controls.h"
#include "../../data/sprites/hud_bar_sprite.h"
#include "hud.h"
#include "../game/game_manager.h"
#include "../game/main_menu.h"
#include "../pickups/pickups.h"
#include "../../data/sprites/inv_sprites.h"
#include "../../data/sprites/menu_sprites.h"
#include "../../data/sprites/numbers/numbers.h"
#include <math.h>
#include <string.h>
Functions
void render_number (int value, pair_t *pos, int max_digits)
Function to render a number.
void render_time_number (int value, pair_t *pos, int max_digits)
Function to render a number filling the initial gaps with 0.
int() render_health_bar (player_info_t *player, double player_dist, double x, double y, double *walls_dist_buf, void *buf)
int() render_crosshair ()
Function to render a red crosshair The crosshair is always placed in the center of the screen according to the values specified.
int() render_gun ()
int() render_object (render_t *render, vector_t *rel_position, double range)
int() render_pickup (player_info_t *p1, pickup_t *pickup, double range, render_t *pickup_render)
int() render_player (player_info_t *p1, player_info_t *p2, double range, render_t *player_render, render_t *health_render, render_t *armor_render)
Renders a player on the screen.
void renders_insert_sorted (render_t *renders, render_t *value, size_t *size)
size_t setup_renders (render_t *renders, double range)
void render_object_renders (render_t *renders, size_t num_renders)
int() draw_walls (__int32_t highest_wall, __int32_t lowest_wall)
int() display_map (double range)
Renders the currently loaded map using the ray casting render technique.
int render_timer ()
int render_game (double range)
void() draw_mouse ()
Draws the mouse.
int display (double range)
General function that renders the screen Chooses what to render based on the state of the game.
Variables
graphics_data g_data
player_info_t player
player_info_t * enemies
size_t num_enemies
unsigned time_counter
map_t map
enum menu_state gun_menu_state
enum game_state state_game
controls_t movm
Function Documentation
draw_walls()
int() draw_walls (__int32_t highest_wall, __int32_t lowest_wall)
Definition at line 407 of file render.c.
References line::color, darken(), line_tex::darken, line_tex::darken_factor, line::draw_higher, line::draw_lower, g_data, graphics_data::h_res, line_tex::last_tex_y, graphics_data::lines, MAX_SPRITE_WIDTH, set_px(), line_tex::step, line_tex::tex, line_tex::tex_hit_x, line_tex::tex_y, and line::texture.
render_game()
int render_game (double range)
Definition at line 602 of file render.c.
References CLOSED, display_map(), display_menu(), DISPLAYING, GAME, get_pickups_size(), get_state(), kbd_ctrl_state::gun_menu, gun_menu_state, player_info::guns, controls_t::kbd_state, player_info::movm, num_enemies, player, render_crosshair(), render_gun(), render_hud(), render_object_renders(), render_timer(), and setup_renders().
render_gun()
int() render_gun ()
Definition at line 121 of file render.c.
References gun::animations, gun_instance::curr_anim, draw_sprite(), g_data, gun_instance::gun, player_info::gun_index, player_info::guns, graphics_data::h_res, player, animated_sprite::sprite, sprite::texture_size, graphics_data::v_res, coordinate::x, pair::x, coordinate::y, and pair::y.
render_health_bar()
int() render_health_bar (player_info_t * player, double player_dist, double x, double y, double * walls_dist_buf, void * buf)
Definition at line 76 of file render.c.
render_object()
int() render_object (render_t * render, vector_t * rel_position, double range)
Definition at line 133 of file render.c.
References render::bounding_box, player_info::camera_plane, determinant(), player_info::direction, render::distance, render::end_pos, render::factor, settings::fov, g_data, graphics_data::h_res, normalize(), render::offset, player, prod_int(), retrieve_settings(), graphics_data::v_res, vec_mag(), vector::x, pair::x, vector::y, and pair::y.
render_object_renders()
void render_object_renders (render_t * renders, size_t num_renders)
Definition at line 391 of file render.c.
References render::bounding_box, render::color, render::distance, draw_darken_rect(), draw_rect_sprite(), render::end_pos, render::factor, render::has_sprite, render::offset, render::sprite, pair::x, and pair::y.
render_pickup()
int() render_pickup (player_info_t * p1, pickup_t * pickup, double range, render_t * pickup_render)
Definition at line 211 of file render.c.
References pickup::animation, circle::center, pickup::collider, player_info::position, render_object(), animated_sprite::sprite, vector::x, and vector::y.
render_timer()
int render_timer ()
Definition at line 586 of file render.c.
References draw_sprite(), g_data, get_round_timer(), graphics_data::h_res, render_number(), render_time_number(), graphics_data::v_res, pair::x, and pair::y.
renders_insert_sorted()
void renders_insert_sorted (render_t * renders, render_t * value, size_t * size)
Definition at line 333 of file render.c.
References render::distance.
setup_renders()
size_t setup_renders (render_t * renders, double range)
Definition at line 356 of file render.c.
References enemies, get_pickup(), get_pickups_size(), num_enemies, pickup::picked_up, pickups_size, player, render_pickup(), render_player(), and renders_insert_sorted().
Variable Documentation
enemies
player_info_t* enemies extern
Definition at line 15 of file player.c.
g_data
graphics_data g_data extern
Definition at line 14 of file video_graphics.c.
gun_menu_state
enum menu_state gun_menu_state extern
Definition at line 15 of file menu.c.
map
map_t map extern
Definition at line 29 of file level_manager.c.
movm
controls_t movm extern
Definition at line 25 of file controls.c.
num_enemies
size_t num_enemies extern
Definition at line 17 of file player.c.
player
player_info_t player extern
Definition at line 13 of file player.c.
state_game
enum game_state state_game extern
time_counter
unsigned time_counter extern
Definition at line 10 of file timer.c.