OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/lib/rtc_controller.c File Reference
rtc_controller.c File Reference
#include <lcom/lcf.h>
#include <lcom/lab5.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include "rtc_controller.h"
#include "rtc.h"
#include "../game/game_manager.h"
Functions
void() reset_pie_state ()
Reset pie state.
date_t * get_curr_date ()
Gets the current's date object.
int bcd_to_decimal (__uint8_t *val)
Converts a bcd number to decimal.
int binary_to_bcd (__uint8_t *val)
Converts a binary number to bcd mode.
int rtc_set_reg (__uint8_t reg)
Chooses what register to use for the next operation.
int rtc_read_reg (__uint8_t reg, __uint8_t *byte)
Reads a specified register.
int rtc_write_reg (__uint8_t reg, __uint8_t byte)
Writes to a specified register.
int rtc_set_date (date_t *date)
Sets the date on a date_t object.
int() rtc_subscribe_int (__uint8_t *bit_no)
Subscribes to the interrupts of the rtc.
int() rtc_unsubscribe_int ()
Unsibscribes rtc interrupts.
int() rtc_int_cause (__uint8_t *cause)
Gets the cause of the interrupt.
int() enable_pie_int ()
Enables periodic interupts.
int() enable_aie_int ()
Enables alarm interrupts.
int() enable_uie_int ()
Enable update interrupts.
int() disable_pie_int ()
Enables periodic interupts.
int() disable_aie_int ()
Enables alarm interrupts.
int() disable_uie_int ()
Enable update interrupts.
int() rtc_set_periodic_500ms ()
Set periodic interrupts to 500ms.
int() rtc_reset_pie ()
Reset periodic interrupts value.
int() rtc_set_alarm (__uint8_t sec, __uint8_t min, __uint8_t hour)
Enables an alarm interrupt.
int() init_rtc_vars ()
Initializes variables to the minix configuration to restore it later.
int() reset_rtc ()
Resets rtc to minix default.
void rtc_ih (void)
RTC Interrupt handler.
Variables
static date_t curr_date
static __uint8_t config_a
static __uint8_t config_b
static __uint8_t pie_state = 0
Variable that indicates how many periodic interrupts it received.
int rtc_subscribe
_Bool alarm_wait = 1
Function Documentation
rtc_read_reg()
int rtc_read_reg (__uint8_t reg, __uint8_t * byte)
Reads a specified register.
Parameters
reg Register to read
[out] byte Output value
Definition at line 65 of file rtc_controller.c.
References RTC_DATA_REG, rtc_set_reg(), and util_sys_inb().
rtc_set_reg()
int rtc_set_reg (__uint8_t reg)
Chooses what register to use for the next operation.
Parameters
reg Register
Definition at line 56 of file rtc_controller.c.
References RTC_ADDR_REG.
rtc_write_reg()
int rtc_write_reg (__uint8_t reg, __uint8_t byte)
Writes to a specified register.
Parameters
reg Register to write
byte Value to write
Definition at line 75 of file rtc_controller.c.
References RTC_DATA_REG, and rtc_set_reg().
Variable Documentation
alarm_wait
_Bool alarm_wait = 1
Definition at line 128 of file rtc_controller.c.
config_a
__uint8_t config_a static
Definition at line 16 of file rtc_controller.c.
config_b
__uint8_t config_b static
Definition at line 17 of file rtc_controller.c.
curr_date
date_t curr_date static
Definition at line 14 of file rtc_controller.c.
pie_state
__uint8_t pie_state = 0 static
Variable that indicates how many periodic interrupts it received.
Definition at line 20 of file rtc_controller.c.
rtc_subscribe
int rtc_subscribe
Definition at line 116 of file rtc_controller.c.