OPERATION M.I.N.I.X.: C:/Virtualization/Setup/MINIX-LCOM/shared/g01/proj/system/lib/sprites.h File Reference
sprites.h File Reference
#include "../utils/data_types.h"
#include <lcom/lcf.h>
#include <stdbool.h>
#include <stdint.h>
Data Structures
struct animated_sprite
Struct that describes an animated sprite.
Macros
#define MAX_SPRITE_WIDTH 80
#define MAX_SPRITE_HEIGHT 80
Typedefs
typedef enum anim_state anim_state_t
Animation state.
typedef struct animated_sprite animated_sprite_t
Struct that describes an animated sprite.
Enumerations
enum anim_state { FINISHED, PROGRESS }
Animation state.
Functions
int load_sprites ()
int free_sprites ()
_Bool() update_anim (animated_sprite_t *anim)
int() load_sprite (xpm_map_t map, sprite_t *sprite)
Loads a sprite from a xpm data type.
int load_background ()
Loads, allocates and stores the sprites relevant to the background.
int free_background ()
Frees the memory allocated by load_background()
int() load_menu_sprites ()
Loads, allocates and stores the sprites relevant to the menu.
int() free_menu_sprites ()
Frees the memory allocated by load_menu_sprites()
int() load_player_sprites ()
Loads, allocates and stores the sprites relevant to the player.
int() load_pickup_sprites ()
Loads, allocates and stores the sprites relevant to the pickups.
int() load_gun_sprites ()
Loads, allocates and stores the sprites relevant to the guns.
int() init_gun_menu_sprites ()
Loads, allocates and stores the sprites relevant to the guns on the menu.
int() free_gun_menu_sprites ()
Frees the memory allocated by init_gun_menu_sprites()
int() free_player_sprites ()
Frees the memory allocated by init_player_sprites()
int() init_cursor_sprite ()
Initializes cursor sprite.
int() free_cursor_sprite ()
Frees the memory allocated by init_cursor_sprite.
int() free_pickup_sprites ()
Frees the memory allocated by load_pickup_sprites.
int() free_gun_sprites ()
Frees the memory allocated by load_gun_sprites()
int load_numbers_sprites ()
Loads, allocates and stores the sprites relevant to number characters.
int free_numbers_sprites ()
Frees the memory allocated by load_numbers_sprites()
int load_hud_sprite ()
Loads, allocates and stores the sprite relevant to the hud.
int free_hud_sprite ()
Frees the memory allocated by load_hud_sprite()
int() init_walls_sprites ()
Initialize wall textures.
int() free_walls_sprites ()
Free wall textures.
Macro Definition Documentation
MAX_SPRITE_HEIGHT
#define MAX_SPRITE_HEIGHT 80
Definition at line 16 of file sprites.h.
MAX_SPRITE_WIDTH
#define MAX_SPRITE_WIDTH 80
Definition at line 15 of file sprites.h.
Typedef Documentation
anim_state_t
typedef enum anim_state anim_state_t
Animation state.
animated_sprite_t
typedef struct animated_sprite animated_sprite_t
Struct that describes an animated sprite.
Enumeration Type Documentation
anim_state
enum anim_state
Animation state.
Enumerator
FINISHED
Finished playing the animation.
PROGRESS
Animation in progress.
Definition at line 21 of file sprites.h.
Function Documentation
free_background()
int free_background ()
Frees the memory allocated by load_background()
Definition at line 131 of file sprites.c.
free_cursor_sprite()
int() free_cursor_sprite ()
Frees the memory allocated by init_cursor_sprite.
Definition at line 419 of file sprites.c.
free_gun_menu_sprites()
int() free_gun_menu_sprites ()
Frees the memory allocated by init_gun_menu_sprites()
Definition at line 349 of file sprites.c.
free_gun_sprites()
int() free_gun_sprites ()
Frees the memory allocated by load_gun_sprites()
Definition at line 400 of file sprites.c.
free_hud_sprite()
int free_hud_sprite ()
Frees the memory allocated by load_hud_sprite()
Definition at line 324 of file sprites.c.
free_menu_sprites()
int() free_menu_sprites ()
Frees the memory allocated by load_menu_sprites()
Definition at line 160 of file sprites.c.
free_numbers_sprites()
int free_numbers_sprites ()
Frees the memory allocated by load_numbers_sprites()
Definition at line 316 of file sprites.c.
free_pickup_sprites()
int() free_pickup_sprites ()
Frees the memory allocated by load_pickup_sprites.
Definition at line 424 of file sprites.c.
free_player_sprites()
int() free_player_sprites ()
Frees the memory allocated by init_player_sprites()
Definition at line 357 of file sprites.c.
free_sprites()
int free_sprites ()
Frees all memory allocated by load_sprites
Definition at line 59 of file sprites.c.
References free_background(), free_cursor_sprite(), free_gun_menu_sprites(), free_gun_sprites(), free_hud_sprite(), free_menu_sprites(), free_numbers_sprites(), free_pickup_sprites(), free_player_sprites(), and free_walls_sprites().
free_walls_sprites()
int() free_walls_sprites ()
Free wall textures.
Definition at line 387 of file sprites.c.
init_cursor_sprite()
int() init_cursor_sprite ()
Initializes cursor sprite.
Definition at line 330 of file sprites.c.
References load_sprite().
init_gun_menu_sprites()
int() init_gun_menu_sprites ()
Loads, allocates and stores the sprites relevant to the guns on the menu.
Definition at line 336 of file sprites.c.
References load_sprite().
init_walls_sprites()
int() init_walls_sprites ()
Initialize wall textures.
Definition at line 371 of file sprites.c.
References load_sprite().
load_background()
int load_background ()
Loads, allocates and stores the sprites relevant to the background.
Definition at line 126 of file sprites.c.
References load_sprite().
load_gun_sprites()
int() load_gun_sprites ()
Loads, allocates and stores the sprites relevant to the guns.
Definition at line 234 of file sprites.c.
References load_sprite().
load_hud_sprite()
int load_hud_sprite ()
Loads, allocates and stores the sprite relevant to the hud.
Definition at line 309 of file sprites.c.
References load_sprite().
load_menu_sprites()
int() load_menu_sprites ()
Loads, allocates and stores the sprites relevant to the menu.
Definition at line 141 of file sprites.c.
References load_sprite().
load_numbers_sprites()
int load_numbers_sprites ()
Loads, allocates and stores the sprites relevant to number characters.
Definition at line 299 of file sprites.c.
References load_sprite().
load_pickup_sprites()
int() load_pickup_sprites ()
Loads, allocates and stores the sprites relevant to the pickups.
Definition at line 205 of file sprites.c.
References load_sprite().
load_player_sprites()
int() load_player_sprites ()
Loads, allocates and stores the sprites relevant to the player.
Definition at line 171 of file sprites.c.
References load_sprite().
load_sprite()
int() load_sprite (xpm_map_t map, sprite_t * sprite)
Loads a sprite from a xpm data type.
Parameters
map Image in xpm_map_t
sprite Sprite pointer
Definition at line 98 of file sprites.c.
References int24::bytes, i24_to_int(), sprite::invis_color, sprite::map, MAX_SPRITE_HEIGHT, MAX_SPRITE_WIDTH, sprite::texture_size, coordinate::x, sprite::x_offset, coordinate::y, and sprite::y_offset.
load_sprites()
int load_sprites ()
Loads all sprites necessary for the project
Returns
Error code
Definition at line 41 of file sprites.c.
References init_cursor_sprite(), init_gun_menu_sprites(), init_walls_sprites(), load_background(), load_disc_background(), load_gun_sprites(), load_hud_sprite(), load_lose_background(), load_menu_sprites(), load_mp_background(), load_numbers_sprites(), load_pickup_sprites(), load_player_sprites(), and load_win_background().
update_anim()
_Bool() update_anim (animated_sprite_t * anim)
Updates an animation
Parameters
anim Pointer to the animation
Returns
true if animation finished
Definition at line 434 of file sprites.c.
References FINISHED, PROGRESS, and time_counter.